/**
 * Expanded UK towns list — targets any town with population ~20,000+.
 *
 * Source: ONS 2021 census + Scotland/Wales/NI equivalents, with some 2023-24
 * revisions. Rounded populations. Includes cities, market towns, seaside
 * resorts, suburban towns, and county towns.
 *
 * Total: ~400 towns, meant to be de-duplicated against ingest-towns.ts's
 * existing 173 by expand-towns.ts (it only INSERTS new ones).
 */

export type ExpandedTown = {
  name: string;
  slug: string;
  countySlug: string;
  pop: number;
};

/** New towns to ADD — de-duped against the existing 173 in ingest-towns.ts. */
export const EXPANDED_TOWNS: ExpandedTown[] = [
  // ── ENGLAND — SOUTH EAST ────────────────────────────────────────────────
  { name: 'Woking',          slug: 'woking',          countySlug: 'surrey',           pop: 105000 },
  { name: 'Guildford',       slug: 'guildford',       countySlug: 'surrey',           pop: 80000  },
  { name: 'Aldershot',       slug: 'aldershot',       countySlug: 'hampshire',        pop: 40000  },
  { name: 'Ashford',         slug: 'ashford',         countySlug: 'kent',             pop: 75000  },
  { name: 'Basingstoke',     slug: 'basingstoke',     countySlug: 'hampshire',        pop: 110000 },
  { name: 'Bracknell',       slug: 'bracknell',       countySlug: 'berkshire',        pop: 85000  },
  { name: 'Crawley',         slug: 'crawley',         countySlug: 'west-sussex',      pop: 115000 },
  { name: 'Eastbourne',      slug: 'eastbourne',      countySlug: 'east-sussex',      pop: 100000 },
  { name: 'Farnborough',     slug: 'farnborough',     countySlug: 'hampshire',        pop: 65000  },
  { name: 'Folkestone',      slug: 'folkestone',      countySlug: 'kent',             pop: 55000  },
  { name: 'Gillingham',      slug: 'gillingham',      countySlug: 'kent',             pop: 105000 },
  { name: 'Gravesend',       slug: 'gravesend',       countySlug: 'kent',             pop: 75000  },
  { name: 'Hastings',        slug: 'hastings',        countySlug: 'east-sussex',      pop: 90000  },
  { name: 'High Wycombe',    slug: 'high-wycombe',    countySlug: 'buckinghamshire',  pop: 125000 },
  { name: 'Horsham',         slug: 'horsham',         countySlug: 'west-sussex',      pop: 55000  },
  { name: 'Maidenhead',      slug: 'maidenhead',      countySlug: 'berkshire',        pop: 75000  },
  { name: 'Maidstone',       slug: 'maidstone',       countySlug: 'kent',             pop: 110000 },
  { name: 'Margate',         slug: 'margate',         countySlug: 'kent',             pop: 60000  },
  { name: 'Newbury',         slug: 'newbury',         countySlug: 'berkshire',        pop: 40000  },
  { name: 'Rochester',       slug: 'rochester',       countySlug: 'kent',             pop: 65000  },
  { name: 'Slough',          slug: 'slough',          countySlug: 'berkshire',        pop: 165000 },
  { name: 'Tunbridge Wells', slug: 'tunbridge-wells', countySlug: 'kent',             pop: 60000  },
  { name: 'Winchester',      slug: 'winchester',      countySlug: 'hampshire',        pop: 50000  },
  { name: 'Windsor',         slug: 'windsor',         countySlug: 'berkshire',        pop: 35000  },
  { name: 'Woking',          slug: 'woking',          countySlug: 'surrey',           pop: 105000 },
  { name: 'Worthing',        slug: 'worthing',        countySlug: 'west-sussex',      pop: 115000 },
  { name: 'Bognor Regis',    slug: 'bognor-regis',    countySlug: 'west-sussex',      pop: 65000  },
  { name: 'Camberley',       slug: 'camberley',       countySlug: 'surrey',           pop: 40000  },
  { name: 'Chichester',      slug: 'chichester',      countySlug: 'west-sussex',      pop: 30000  },
  { name: 'Redhill',         slug: 'redhill',         countySlug: 'surrey',           pop: 45000  },
  { name: 'Reigate',         slug: 'reigate',         countySlug: 'surrey',           pop: 55000  },
  { name: 'Dartford',        slug: 'dartford',        countySlug: 'kent',             pop: 100000 },
  { name: 'Sittingbourne',   slug: 'sittingbourne',   countySlug: 'kent',             pop: 60000  },
  { name: 'Havant',          slug: 'havant',          countySlug: 'hampshire',        pop: 45000  },
  { name: 'Fareham',         slug: 'fareham',         countySlug: 'hampshire',        pop: 45000  },
  { name: 'Gosport',         slug: 'gosport',         countySlug: 'hampshire',        pop: 85000  },
  { name: 'Andover',         slug: 'andover',         countySlug: 'hampshire',        pop: 55000  },
  { name: 'Waterlooville',   slug: 'waterlooville',   countySlug: 'hampshire',        pop: 65000  },
  { name: 'Bicester',        slug: 'bicester',        countySlug: 'oxfordshire',      pop: 40000  },
  { name: 'Banbury',         slug: 'banbury',         countySlug: 'oxfordshire',      pop: 55000  },
  { name: 'Witney',          slug: 'witney',          countySlug: 'oxfordshire',      pop: 30000  },
  { name: 'Abingdon',        slug: 'abingdon',        countySlug: 'oxfordshire',      pop: 35000  },
  { name: 'Aylesbury',       slug: 'aylesbury-town',  countySlug: 'buckinghamshire',  pop: 75000  },
  { name: 'Chesham',         slug: 'chesham',         countySlug: 'buckinghamshire',  pop: 25000  },
  { name: 'Amersham',        slug: 'amersham',        countySlug: 'buckinghamshire',  pop: 25000  },
  { name: 'Berkhamsted',     slug: 'berkhamsted',     countySlug: 'hertfordshire',    pop: 20000  },
  { name: 'Hemel Hempstead', slug: 'hemel-hempstead', countySlug: 'hertfordshire',    pop: 100000 },
  { name: 'Stevenage',       slug: 'stevenage',       countySlug: 'hertfordshire',    pop: 90000  },
  { name: 'Watford',         slug: 'watford',         countySlug: 'hertfordshire',    pop: 130000 },
  { name: 'St Albans',       slug: 'st-albans',       countySlug: 'hertfordshire',    pop: 85000  },
  { name: 'Welwyn Garden City', slug: 'welwyn-garden-city', countySlug: 'hertfordshire', pop: 50000 },
  { name: 'Hatfield',        slug: 'hatfield',        countySlug: 'hertfordshire',    pop: 40000  },
  { name: 'Hitchin',         slug: 'hitchin',         countySlug: 'hertfordshire',    pop: 35000  },
  { name: 'Letchworth',      slug: 'letchworth',      countySlug: 'hertfordshire',    pop: 35000  },
  { name: 'Cheshunt',        slug: 'cheshunt',        countySlug: 'hertfordshire',    pop: 55000  },
  { name: 'Bishop\'s Stortford', slug: 'bishops-stortford', countySlug: 'hertfordshire', pop: 40000 },

  // ── ENGLAND — SOUTH WEST ────────────────────────────────────────────────
  { name: 'Bath',            slug: 'bath-town',       countySlug: 'somerset',         pop: 95000  },
  { name: 'Bournemouth',     slug: 'bournemouth',     countySlug: 'dorset',           pop: 200000 },
  { name: 'Poole',           slug: 'poole',           countySlug: 'dorset',           pop: 150000 },
  { name: 'Weymouth',        slug: 'weymouth',        countySlug: 'dorset',           pop: 55000  },
  { name: 'Cheltenham',      slug: 'cheltenham',      countySlug: 'gloucestershire',  pop: 120000 },
  { name: 'Exeter',          slug: 'exeter',          countySlug: 'devon',            pop: 130000 },
  { name: 'Torquay',         slug: 'torquay',         countySlug: 'devon',            pop: 65000  },
  { name: 'Paignton',        slug: 'paignton',        countySlug: 'devon',            pop: 50000  },
  { name: 'Barnstaple',      slug: 'barnstaple',      countySlug: 'devon',            pop: 35000  },
  { name: 'Newton Abbot',    slug: 'newton-abbot',    countySlug: 'devon',            pop: 25000  },
  { name: 'Bideford',        slug: 'bideford',        countySlug: 'devon',            pop: 20000  },
  { name: 'Truro',           slug: 'truro',           countySlug: 'cornwall',         pop: 25000  },
  { name: 'St Austell',      slug: 'st-austell',      countySlug: 'cornwall',         pop: 30000  },
  { name: 'Falmouth',        slug: 'falmouth',        countySlug: 'cornwall',         pop: 25000  },
  { name: 'Penzance',        slug: 'penzance',        countySlug: 'cornwall',         pop: 20000  },
  { name: 'Newquay',         slug: 'newquay',         countySlug: 'cornwall',         pop: 25000  },
  { name: 'Camborne',        slug: 'camborne',        countySlug: 'cornwall',         pop: 20000  },
  { name: 'Redruth',         slug: 'redruth',         countySlug: 'cornwall',         pop: 15000  },
  { name: 'Salisbury',       slug: 'salisbury',       countySlug: 'wiltshire',        pop: 45000  },
  { name: 'Swindon',         slug: 'swindon',         countySlug: 'wiltshire',        pop: 185000 },
  { name: 'Trowbridge',      slug: 'trowbridge',      countySlug: 'wiltshire',        pop: 40000  },
  { name: 'Chippenham',      slug: 'chippenham',      countySlug: 'wiltshire',        pop: 40000  },
  { name: 'Gloucester',      slug: 'gloucester',      countySlug: 'gloucestershire',  pop: 135000 },
  { name: 'Stroud',          slug: 'stroud',          countySlug: 'gloucestershire',  pop: 35000  },
  { name: 'Yeovil',          slug: 'yeovil-town',     countySlug: 'somerset',         pop: 45000  },
  { name: 'Taunton',         slug: 'taunton-town',    countySlug: 'somerset',         pop: 70000  },
  { name: 'Bridgwater',      slug: 'bridgwater-town', countySlug: 'somerset',         pop: 40000  },
  { name: 'Frome',           slug: 'frome-town',      countySlug: 'somerset',         pop: 28000  },
  { name: 'Wells',           slug: 'wells-town',      countySlug: 'somerset',         pop: 12000  },
  { name: 'Weston-super-Mare', slug: 'weston-super-mare-town', countySlug: 'somerset', pop: 80000 },

  // ── ENGLAND — EAST ──────────────────────────────────────────────────────
  { name: 'Chelmsford',      slug: 'chelmsford',      countySlug: 'essex',            pop: 175000 },
  { name: 'Colchester',      slug: 'colchester',      countySlug: 'essex',            pop: 195000 },
  { name: 'Basildon',        slug: 'basildon',        countySlug: 'essex',            pop: 115000 },
  { name: 'Southend-on-Sea', slug: 'southend-on-sea', countySlug: 'essex',            pop: 185000 },
  { name: 'Braintree',       slug: 'braintree',       countySlug: 'essex',            pop: 55000  },
  { name: 'Harlow',          slug: 'harlow',          countySlug: 'essex',            pop: 85000  },
  { name: 'Loughton',        slug: 'loughton',        countySlug: 'essex',            pop: 30000  },
  { name: 'Clacton-on-Sea',  slug: 'clacton-on-sea',  countySlug: 'essex',            pop: 55000  },
  { name: 'Grays',           slug: 'grays',           countySlug: 'essex',            pop: 65000  },
  { name: 'Cambridge',       slug: 'cambridge',       countySlug: 'cambridgeshire',   pop: 145000 },
  { name: 'Peterborough',    slug: 'peterborough',    countySlug: 'cambridgeshire',   pop: 200000 },
  { name: 'Huntingdon',      slug: 'huntingdon',      countySlug: 'cambridgeshire',   pop: 25000  },
  { name: 'Ely',             slug: 'ely',             countySlug: 'cambridgeshire',   pop: 20000  },
  { name: 'St Neots',        slug: 'st-neots',        countySlug: 'cambridgeshire',   pop: 32000  },
  { name: 'Wisbech',         slug: 'wisbech',         countySlug: 'cambridgeshire',   pop: 30000  },
  { name: 'Norwich',         slug: 'norwich-town',    countySlug: 'norfolk',          pop: 145000 },
  { name: 'Great Yarmouth',  slug: 'great-yarmouth',  countySlug: 'norfolk',          pop: 40000  },
  { name: 'King\'s Lynn',    slug: 'kings-lynn',      countySlug: 'norfolk',          pop: 45000  },
  { name: 'Ipswich',         slug: 'ipswich',         countySlug: 'suffolk',          pop: 145000 },
  { name: 'Bury St Edmunds', slug: 'bury-st-edmunds', countySlug: 'suffolk',          pop: 45000  },
  { name: 'Lowestoft',       slug: 'lowestoft',       countySlug: 'suffolk',          pop: 70000  },
  { name: 'Bedford',         slug: 'bedford',         countySlug: 'bedfordshire',     pop: 110000 },
  { name: 'Dunstable',       slug: 'dunstable',       countySlug: 'bedfordshire',     pop: 40000  },
  { name: 'Leighton Buzzard', slug: 'leighton-buzzard', countySlug: 'bedfordshire',   pop: 40000  },

  // ── ENGLAND — MIDLANDS ──────────────────────────────────────────────────
  { name: 'Leicester',       slug: 'leicester',       countySlug: 'leicestershire',   pop: 370000 },
  { name: 'Loughborough',    slug: 'loughborough',    countySlug: 'leicestershire',   pop: 60000  },
  { name: 'Hinckley',        slug: 'hinckley',        countySlug: 'leicestershire',   pop: 50000  },
  { name: 'Coalville',       slug: 'coalville',       countySlug: 'leicestershire',   pop: 35000  },
  { name: 'Melton Mowbray',  slug: 'melton-mowbray',  countySlug: 'leicestershire',   pop: 30000  },
  { name: 'Kettering',       slug: 'kettering',       countySlug: 'northamptonshire', pop: 55000  },
  { name: 'Corby',           slug: 'corby',           countySlug: 'northamptonshire', pop: 65000  },
  { name: 'Wellingborough',  slug: 'wellingborough',  countySlug: 'northamptonshire', pop: 55000  },
  { name: 'Rushden',         slug: 'rushden',         countySlug: 'northamptonshire', pop: 30000  },
  { name: 'Solihull',        slug: 'solihull',        countySlug: 'west-midlands',    pop: 125000 },
  { name: 'Walsall',         slug: 'walsall',         countySlug: 'west-midlands',    pop: 285000 },
  { name: 'Dudley',          slug: 'dudley',          countySlug: 'west-midlands',    pop: 315000 },
  { name: 'West Bromwich',   slug: 'west-bromwich',   countySlug: 'west-midlands',    pop: 80000  },
  { name: 'Sutton Coldfield', slug: 'sutton-coldfield', countySlug: 'west-midlands',  pop: 100000 },
  { name: 'Halesowen',       slug: 'halesowen',       countySlug: 'west-midlands',    pop: 60000  },
  { name: 'Stourbridge',     slug: 'stourbridge',     countySlug: 'west-midlands',    pop: 60000  },
  { name: 'Nuneaton',        slug: 'nuneaton',        countySlug: 'warwickshire',     pop: 90000  },
  { name: 'Rugby',           slug: 'rugby',           countySlug: 'warwickshire',     pop: 75000  },
  { name: 'Leamington Spa',  slug: 'leamington-spa',  countySlug: 'warwickshire',     pop: 50000  },
  { name: 'Warwick',         slug: 'warwick',         countySlug: 'warwickshire',     pop: 35000  },
  { name: 'Stratford-upon-Avon', slug: 'stratford-upon-avon', countySlug: 'warwickshire', pop: 30000 },
  { name: 'Worcester',       slug: 'worcester',       countySlug: 'worcestershire',   pop: 105000 },
  { name: 'Kidderminster',   slug: 'kidderminster',   countySlug: 'worcestershire',   pop: 55000  },
  { name: 'Redditch',        slug: 'redditch',        countySlug: 'worcestershire',   pop: 85000  },
  { name: 'Bromsgrove',      slug: 'bromsgrove',      countySlug: 'worcestershire',   pop: 30000  },
  { name: 'Shrewsbury',      slug: 'shrewsbury',      countySlug: 'shropshire',       pop: 75000  },
  { name: 'Telford',         slug: 'telford-town',    countySlug: 'shropshire',       pop: 150000 },
  { name: 'Hereford',        slug: 'hereford',        countySlug: 'herefordshire',    pop: 55000  },
  { name: 'Chesterfield',    slug: 'chesterfield',    countySlug: 'derbyshire',       pop: 90000  },
  { name: 'Long Eaton',      slug: 'long-eaton',      countySlug: 'derbyshire',       pop: 40000  },
  { name: 'Ilkeston',        slug: 'ilkeston',        countySlug: 'derbyshire',       pop: 35000  },
  { name: 'Ripley',          slug: 'ripley',          countySlug: 'derbyshire',       pop: 30000  },
  { name: 'Buxton',          slug: 'buxton',          countySlug: 'derbyshire',       pop: 25000  },
  { name: 'Mansfield',       slug: 'mansfield',       countySlug: 'nottinghamshire',  pop: 110000 },
  { name: 'Newark',          slug: 'newark',          countySlug: 'nottinghamshire',  pop: 30000  },
  { name: 'Worksop',         slug: 'worksop',         countySlug: 'nottinghamshire',  pop: 45000  },
  { name: 'Sutton-in-Ashfield', slug: 'sutton-in-ashfield', countySlug: 'nottinghamshire', pop: 45000 },
  { name: 'Lincoln',         slug: 'lincoln',         countySlug: 'lincolnshire',     pop: 100000 },
  { name: 'Grimsby',         slug: 'grimsby',         countySlug: 'lincolnshire',     pop: 90000  },
  { name: 'Scunthorpe',      slug: 'scunthorpe',      countySlug: 'lincolnshire',     pop: 80000  },
  { name: 'Boston',          slug: 'boston',          countySlug: 'lincolnshire',     pop: 45000  },
  { name: 'Grantham',        slug: 'grantham',        countySlug: 'lincolnshire',     pop: 45000  },
  { name: 'Skegness',        slug: 'skegness',        countySlug: 'lincolnshire',     pop: 20000  },
  { name: 'Spalding',        slug: 'spalding',        countySlug: 'lincolnshire',     pop: 30000  },
  { name: 'Stoke-on-Trent',  slug: 'stoke-on-trent-town', countySlug: 'staffordshire', pop: 260000 },
  { name: 'Stafford',        slug: 'stafford',        countySlug: 'staffordshire',    pop: 70000  },
  { name: 'Burton upon Trent', slug: 'burton-upon-trent', countySlug: 'staffordshire', pop: 75000 },
  { name: 'Cannock',         slug: 'cannock',         countySlug: 'staffordshire',    pop: 30000  },
  { name: 'Tamworth',        slug: 'tamworth',        countySlug: 'staffordshire',    pop: 80000  },
  { name: 'Lichfield',       slug: 'lichfield',       countySlug: 'staffordshire',    pop: 35000  },
  { name: 'Newcastle-under-Lyme', slug: 'newcastle-under-lyme', countySlug: 'staffordshire', pop: 75000 },

  // ── ENGLAND — NORTH WEST ────────────────────────────────────────────────
  { name: 'Bolton',          slug: 'bolton',          countySlug: 'manchester', pop: 195000 },
  { name: 'Stockport',       slug: 'stockport',       countySlug: 'manchester', pop: 300000 },
  { name: 'Oldham',          slug: 'oldham',          countySlug: 'manchester', pop: 105000 },
  { name: 'Rochdale',        slug: 'rochdale',        countySlug: 'manchester', pop: 110000 },
  { name: 'Bury',            slug: 'bury',            countySlug: 'manchester', pop: 80000  },
  { name: 'Wigan',           slug: 'wigan',           countySlug: 'manchester', pop: 105000 },
  { name: 'Salford',         slug: 'salford',         countySlug: 'manchester', pop: 105000 },
  { name: 'Sale',            slug: 'sale',            countySlug: 'manchester', pop: 55000  },
  { name: 'Altrincham',      slug: 'altrincham-town', countySlug: 'manchester', pop: 55000  },
  { name: 'Ashton-under-Lyne', slug: 'ashton-under-lyne', countySlug: 'manchester', pop: 45000 },
  { name: 'Blackpool',       slug: 'blackpool',       countySlug: 'lancashire',       pop: 140000 },
  { name: 'Blackburn',       slug: 'blackburn',       countySlug: 'lancashire',       pop: 120000 },
  { name: 'Burnley',         slug: 'burnley',         countySlug: 'lancashire',       pop: 75000  },
  { name: 'Chorley',         slug: 'chorley',         countySlug: 'lancashire',       pop: 40000  },
  { name: 'Lancaster',       slug: 'lancaster',       countySlug: 'lancashire',       pop: 55000  },
  { name: 'Morecambe',       slug: 'morecambe',       countySlug: 'lancashire',       pop: 35000  },
  { name: 'Fleetwood',       slug: 'fleetwood',       countySlug: 'lancashire',       pop: 25000  },
  { name: 'Nelson',          slug: 'nelson',          countySlug: 'lancashire',       pop: 30000  },
  { name: 'Accrington',      slug: 'accrington',      countySlug: 'lancashire',       pop: 35000  },
  { name: 'St Helens',       slug: 'st-helens',       countySlug: 'merseyside',       pop: 105000 },
  { name: 'Southport',       slug: 'southport',       countySlug: 'merseyside',       pop: 90000  },
  { name: 'Bootle',          slug: 'bootle',          countySlug: 'merseyside',       pop: 55000  },
  { name: 'Birkenhead',      slug: 'birkenhead-town', countySlug: 'merseyside',       pop: 90000  },
  { name: 'Wallasey',        slug: 'wallasey',        countySlug: 'merseyside',       pop: 60000  },
  { name: 'Chester',         slug: 'chester',         countySlug: 'cheshire',         pop: 80000  },
  { name: 'Warrington',      slug: 'warrington',      countySlug: 'cheshire',         pop: 175000 },
  { name: 'Crewe',           slug: 'crewe',           countySlug: 'cheshire',         pop: 75000  },
  { name: 'Macclesfield',    slug: 'macclesfield',    countySlug: 'cheshire',         pop: 55000  },
  { name: 'Ellesmere Port',  slug: 'ellesmere-port',  countySlug: 'cheshire',         pop: 55000  },
  { name: 'Runcorn',         slug: 'runcorn',         countySlug: 'cheshire',         pop: 60000  },
  { name: 'Widnes',          slug: 'widnes',          countySlug: 'cheshire',         pop: 60000  },
  { name: 'Northwich',       slug: 'northwich',       countySlug: 'cheshire',         pop: 30000  },
  { name: 'Winsford',        slug: 'winsford',        countySlug: 'cheshire',         pop: 35000  },
  { name: 'Wilmslow',        slug: 'wilmslow',        countySlug: 'cheshire',         pop: 25000  },
  { name: 'Carlisle',        slug: 'carlisle',        countySlug: 'cumbria',          pop: 75000  },
  { name: 'Barrow-in-Furness', slug: 'barrow-in-furness', countySlug: 'cumbria',      pop: 55000  },
  { name: 'Kendal',          slug: 'kendal',          countySlug: 'cumbria',          pop: 30000  },
  { name: 'Workington',      slug: 'workington',      countySlug: 'cumbria',          pop: 25000  },
  { name: 'Whitehaven',      slug: 'whitehaven',      countySlug: 'cumbria',          pop: 25000  },
  { name: 'Penrith',         slug: 'penrith',         countySlug: 'cumbria',          pop: 15000  },

  // ── ENGLAND — YORKSHIRE ─────────────────────────────────────────────────
  { name: 'York',            slug: 'york',            countySlug: 'north-yorkshire',  pop: 155000 },
  { name: 'Harrogate',       slug: 'harrogate',       countySlug: 'north-yorkshire',  pop: 75000  },
  { name: 'Scarborough',     slug: 'scarborough',     countySlug: 'north-yorkshire',  pop: 60000  },
  { name: 'Middlesbrough',   slug: 'middlesbrough',   countySlug: 'north-yorkshire',  pop: 140000 },
  { name: 'Northallerton',   slug: 'northallerton',   countySlug: 'north-yorkshire',  pop: 17000  },
  { name: 'Bridlington',     slug: 'bridlington',     countySlug: 'east-yorkshire',   pop: 35000  },
  { name: 'Beverley',        slug: 'beverley',        countySlug: 'east-yorkshire',   pop: 30000  },
  { name: 'Doncaster',       slug: 'doncaster',       countySlug: 'south-yorkshire',  pop: 155000 },
  { name: 'Rotherham',       slug: 'rotherham',       countySlug: 'south-yorkshire',  pop: 110000 },
  { name: 'Barnsley',        slug: 'barnsley',        countySlug: 'south-yorkshire',  pop: 95000  },
  { name: 'Wakefield',       slug: 'wakefield-town',  countySlug: 'west-yorkshire',   pop: 100000 },
  { name: 'Huddersfield',    slug: 'huddersfield',    countySlug: 'west-yorkshire',   pop: 165000 },
  { name: 'Halifax',         slug: 'halifax',         countySlug: 'west-yorkshire',   pop: 90000  },
  { name: 'Dewsbury',        slug: 'dewsbury',        countySlug: 'west-yorkshire',   pop: 65000  },
  { name: 'Batley',          slug: 'batley',          countySlug: 'west-yorkshire',   pop: 50000  },
  { name: 'Keighley',        slug: 'keighley',        countySlug: 'west-yorkshire',   pop: 55000  },
  { name: 'Pontefract',      slug: 'pontefract',      countySlug: 'west-yorkshire',   pop: 30000  },
  { name: 'Castleford',      slug: 'castleford',      countySlug: 'west-yorkshire',   pop: 40000  },

  // ── ENGLAND — NORTH EAST ────────────────────────────────────────────────
  { name: 'Sunderland',      slug: 'sunderland',      countySlug: 'tyne-and-wear',    pop: 175000 },
  { name: 'Gateshead',       slug: 'gateshead',       countySlug: 'tyne-and-wear',    pop: 120000 },
  { name: 'South Shields',   slug: 'south-shields',   countySlug: 'tyne-and-wear',    pop: 75000  },
  { name: 'North Shields',   slug: 'north-shields',   countySlug: 'tyne-and-wear',    pop: 40000  },
  { name: 'Washington',      slug: 'washington',      countySlug: 'tyne-and-wear',    pop: 65000  },
  { name: 'Darlington',      slug: 'darlington',      countySlug: 'county-durham',    pop: 95000  },
  { name: 'Hartlepool',      slug: 'hartlepool',      countySlug: 'county-durham',    pop: 90000  },
  { name: 'Stockton-on-Tees', slug: 'stockton-on-tees', countySlug: 'county-durham',  pop: 85000  },
  { name: 'Durham',          slug: 'durham-town',     countySlug: 'county-durham',    pop: 50000  },
  { name: 'Consett',         slug: 'consett',         countySlug: 'county-durham',    pop: 25000  },
  { name: 'Blyth',           slug: 'blyth',           countySlug: 'northumberland',   pop: 40000  },
  { name: 'Ashington',       slug: 'ashington',       countySlug: 'northumberland',   pop: 30000  },
  { name: 'Cramlington',     slug: 'cramlington',     countySlug: 'northumberland',   pop: 30000  },
  { name: 'Hexham',          slug: 'hexham',          countySlug: 'northumberland',   pop: 12000  },

  // ── WALES ───────────────────────────────────────────────────────────────
  // Newport (Wales) — Wales's 3rd largest city, its own unitary authority
  { name: 'Newport',         slug: 'newport-town',    countySlug: 'newport',          pop: 155000 },
  { name: 'Wrexham',         slug: 'wrexham-town',    countySlug: 'wrexham',          pop: 65000  },
  { name: 'Rhondda',         slug: 'rhondda',         countySlug: 'rhondda-cynon-taf', pop: 70000  },
  { name: 'Aberdare',        slug: 'aberdare',        countySlug: 'rhondda-cynon-taf', pop: 30000 },
  { name: 'Pontypridd',      slug: 'pontypridd',      countySlug: 'rhondda-cynon-taf', pop: 32000 },
  { name: 'Merthyr Tydfil',  slug: 'merthyr-tydfil-town', countySlug: 'merthyr-tydfil', pop: 45000 },
  { name: 'Barry',           slug: 'barry',           countySlug: 'vale-of-glamorgan', pop: 55000 },
  { name: 'Penarth',         slug: 'penarth',         countySlug: 'vale-of-glamorgan', pop: 27000 },
  { name: 'Neath',           slug: 'neath',           countySlug: 'neath-port-talbot', pop: 50000 },
  { name: 'Port Talbot',     slug: 'port-talbot',     countySlug: 'neath-port-talbot', pop: 40000 },
  { name: 'Bridgend',        slug: 'bridgend-town',   countySlug: 'bridgend',         pop: 45000  },
  { name: 'Porthcawl',       slug: 'porthcawl',       countySlug: 'bridgend',         pop: 15000  },
  { name: 'Llanelli',        slug: 'llanelli',        countySlug: 'carmarthenshire',  pop: 45000  },
  { name: 'Carmarthen',      slug: 'carmarthen',      countySlug: 'carmarthenshire',  pop: 15000  },
  { name: 'Ammanford',       slug: 'ammanford',       countySlug: 'carmarthenshire',  pop: 13000  },
  { name: 'Aberystwyth',     slug: 'aberystwyth',     countySlug: 'ceredigion',       pop: 18000  },
  { name: 'Cardigan',        slug: 'cardigan',        countySlug: 'ceredigion',       pop: 4500   },
  { name: 'Bangor',          slug: 'bangor',          countySlug: 'gwynedd',          pop: 18000  },
  { name: 'Caernarfon',      slug: 'caernarfon',      countySlug: 'gwynedd',          pop: 10000  },
  { name: 'Porthmadog',      slug: 'porthmadog',      countySlug: 'gwynedd',          pop: 4200   },
  { name: 'Pwllheli',        slug: 'pwllheli',        countySlug: 'gwynedd',          pop: 4100   },
  { name: 'Holyhead',        slug: 'holyhead',        countySlug: 'anglesey',         pop: 12000  },
  { name: 'Llangefni',       slug: 'llangefni',       countySlug: 'anglesey',         pop: 5000   },
  { name: 'Llandudno',       slug: 'llandudno',       countySlug: 'conwy',            pop: 20000  },
  { name: 'Colwyn Bay',      slug: 'colwyn-bay',      countySlug: 'conwy',            pop: 32000  },
  { name: 'Rhyl',            slug: 'rhyl',            countySlug: 'denbighshire',     pop: 26000  },
  { name: 'Prestatyn',       slug: 'prestatyn',       countySlug: 'denbighshire',     pop: 19000  },
  { name: 'Denbigh',         slug: 'denbigh',         countySlug: 'denbighshire',     pop: 9000   },
  { name: 'Ruthin',          slug: 'ruthin',          countySlug: 'denbighshire',     pop: 5500   },
  { name: 'Mold',            slug: 'mold',            countySlug: 'flintshire',       pop: 11000  },
  { name: 'Buckley',         slug: 'buckley',         countySlug: 'flintshire',       pop: 15000  },
  { name: 'Connahs Quay',    slug: 'connahs-quay',    countySlug: 'flintshire',       pop: 16000  },
  { name: 'Flint',           slug: 'flint',           countySlug: 'flintshire',       pop: 13000  },
  { name: 'Haverfordwest',   slug: 'haverfordwest',   countySlug: 'pembrokeshire',    pop: 14000  },
  { name: 'Milford Haven',   slug: 'milford-haven',   countySlug: 'pembrokeshire',    pop: 13000  },
  { name: 'Pembroke',        slug: 'pembroke',        countySlug: 'pembrokeshire',    pop: 7500   },
  { name: 'Tenby',           slug: 'tenby',           countySlug: 'pembrokeshire',    pop: 4700   },
  { name: 'Newtown',         slug: 'newtown-powys',   countySlug: 'powys',            pop: 12000  },
  { name: 'Brecon',          slug: 'brecon',          countySlug: 'powys',            pop: 8000   },
  { name: 'Welshpool',       slug: 'welshpool',       countySlug: 'powys',            pop: 6600   },
  { name: 'Llandrindod Wells', slug: 'llandrindod-wells', countySlug: 'powys',        pop: 5000   },
  { name: 'Chepstow',        slug: 'chepstow',        countySlug: 'monmouthshire',    pop: 13000  },
  { name: 'Abergavenny',     slug: 'abergavenny',     countySlug: 'monmouthshire',    pop: 12000  },
  { name: 'Monmouth',        slug: 'monmouth',        countySlug: 'monmouthshire',    pop: 10500  },
  { name: 'Caerphilly',      slug: 'caerphilly-town', countySlug: 'caerphilly',       pop: 41000  },
  { name: 'Bargoed',         slug: 'bargoed',         countySlug: 'caerphilly',       pop: 13500  },
  { name: 'Blackwood',       slug: 'blackwood',       countySlug: 'caerphilly',       pop: 8000   },
  { name: 'Ebbw Vale',       slug: 'ebbw-vale',       countySlug: 'blaenau-gwent',    pop: 20000  },
  { name: 'Tredegar',        slug: 'tredegar',        countySlug: 'blaenau-gwent',    pop: 15000  },
  { name: 'Pontypool',       slug: 'pontypool',       countySlug: 'torfaen',          pop: 35000  },
  { name: 'Cwmbran',         slug: 'cwmbran',         countySlug: 'torfaen',          pop: 47000  },

  // ── SCOTLAND ────────────────────────────────────────────────────────────
  { name: 'Paisley',         slug: 'paisley',         countySlug: 'renfrewshire',     pop: 75000  },
  { name: 'East Kilbride',   slug: 'east-kilbride',   countySlug: 'south-lanarkshire', pop: 75000 },
  { name: 'Hamilton',        slug: 'hamilton',        countySlug: 'south-lanarkshire', pop: 55000 },
  { name: 'Livingston',      slug: 'livingston',      countySlug: 'west-lothian',     pop: 58000  },
  { name: 'Cumbernauld',     slug: 'cumbernauld',     countySlug: 'north-lanarkshire', pop: 55000 },
  { name: 'Kirkcaldy',       slug: 'kirkcaldy',       countySlug: 'fife',             pop: 50000  },
  { name: 'Dunfermline',     slug: 'dunfermline',     countySlug: 'fife',             pop: 55000  },
  { name: 'Perth',           slug: 'perth',           countySlug: 'perth-and-kinross', pop: 50000 },
  { name: 'Ayr',             slug: 'ayr',             countySlug: 'ayrshire',   pop: 47000  },
  { name: 'Kilmarnock',      slug: 'kilmarnock',      countySlug: 'ayrshire',    pop: 45000  },
  { name: 'Greenock',        slug: 'greenock',        countySlug: 'inverclyde',       pop: 43000  },
  { name: 'Inverness',       slug: 'inverness',       countySlug: 'highland',         pop: 65000  },
  { name: 'Stirling',        slug: 'stirling-town',   countySlug: 'stirlingshire-and-clackmannanshire',         pop: 38000  },
  { name: 'Falkirk',         slug: 'falkirk-town',    countySlug: 'stirlingshire-and-clackmannanshire',          pop: 35000  },
  { name: 'Motherwell',      slug: 'motherwell',      countySlug: 'north-lanarkshire', pop: 32000 },
  { name: 'Airdrie',         slug: 'airdrie',         countySlug: 'north-lanarkshire', pop: 37000 },
  { name: 'Coatbridge',      slug: 'coatbridge',      countySlug: 'north-lanarkshire', pop: 43000 },

  // ── NORTHERN IRELAND ────────────────────────────────────────────────────
  { name: 'Londonderry',     slug: 'londonderry',     countySlug: 'londonderry', pop: 105000 },
  { name: 'Lisburn',         slug: 'lisburn',         countySlug: 'county-antrim',    pop: 45000  },
  { name: 'Newry',           slug: 'newry',           countySlug: 'armagh',    pop: 27000  },
  { name: 'Bangor',          slug: 'bangor-ni',       countySlug: 'county-down',      pop: 65000  },
  { name: 'Craigavon',       slug: 'craigavon',       countySlug: 'armagh',    pop: 60000  },
  { name: 'Ballymena',       slug: 'ballymena',       countySlug: 'county-antrim',    pop: 30000  },
  { name: 'Newtownabbey',    slug: 'newtownabbey',    countySlug: 'county-antrim',    pop: 65000  },
  { name: 'Carrickfergus',   slug: 'carrickfergus',   countySlug: 'county-antrim',    pop: 30000  },
  { name: 'Antrim',          slug: 'antrim',          countySlug: 'county-antrim',    pop: 25000  },
  { name: 'Newtownards',     slug: 'newtownards',     countySlug: 'county-down',      pop: 30000  },
  { name: 'Armagh',          slug: 'armagh-town',     countySlug: 'armagh',    pop: 15000  },
  { name: 'Omagh',           slug: 'omagh',           countySlug: 'tyrone',    pop: 22000  },
  { name: 'Enniskillen',     slug: 'enniskillen',     countySlug: 'fermanagh', pop: 14000  },
];

/** Total count for logging. */
export const EXPANDED_COUNT = EXPANDED_TOWNS.length;
