/**
 * Ingest 40 generic-term landers as genericTerm documents in Sanity.
 *
 * Modifier × service-noun matrix designed to capture transactional and
 * informational long-tail search demand around UK direct cremation.
 *
 * Output: 40 documents at /services/[slug]/
 *
 * Usage:  npx tsx scripts/ingest-generics.ts
 */
import { createClient } from '@sanity/client';
import { Linkifier } from './lib/linkify';
import { GAP_PAGES } from './generics-gap-pages';
import { GAP_PAGES_BATCH_2 } from './generics-gap-pages-batch-2';

function enrichBlocks(blocks: any[], slug: string): any[] {
  if (!Array.isArray(blocks)) return blocks;
  const linkifier = new Linkifier({ currentSlug: slug });
  return blocks.map(block => {
    if (block?.style === 'normal' && block?.children?.[0]?.text && (!block.markDefs || block.markDefs.length === 0)) {
      return linkifier.pt(block.children[0].text);
    }
    return block;
  });
}

const PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || '80kiihr6';
const DATASET    = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
const TOKEN      = process.env.SANITY_API_WRITE_TOKEN;
if (!TOKEN) throw new Error('Set SANITY_API_WRITE_TOKEN before running ingestion.');
const client = createClient({ projectId: PROJECT_ID, dataset: DATASET, apiVersion: '2024-10-01', useCdn: false, token: TOKEN });

const pt = (text: string) => ({ _type: 'block', style: 'normal', children: [{ _type: 'span', text }], markDefs: [] });
const h2 = (text: string) => ({ _type: 'block', style: 'h2', children: [{ _type: 'span', text }], markDefs: [] });

// ============================================================
// 40 GENERIC TERM LANDERS
// ============================================================

type Generic = {
  slug: string;
  title: string;
  modifier?: string;
  serviceNoun: string;
  intentMatch: string;     // brief intent description
  longForm: any[];
  faqs: Array<{ q: string; a: string }>;
};

// Helper — standard closing CTA block used at the bottom of every lander
const ctaSection = (slug: string) => [
  h2('How to arrange a Best Direct Cremation'),
  pt(`If you're ready to arrange a Best Direct Cremation, the next step is one phone call: 0333 242 1405. A real person answers — 24 hours a day. No high-pressure sales, no waiting on hold. We take a few essential details, dispatch a vetted local funeral director to take your loved one into care, and handle every piece of paperwork from there.`),
  pt(`Best Direct Cremation costs £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection fee if the person who has died is not at a hospital or coroner's mortuary (maximum total £1,749). We are NAFD- or SAIF-accredited through every partner in our network, and every cremation is delivered locally — never centralised.`),
];

// Shared standard FAQs
const standardFaqs = [
  { q: 'How much does a Best Direct Cremation cost?', a: '£1,499 all-inclusive. The only optional cost is a £250 Priority Care collection fee if the person who has died is not at a hospital or coroner\'s mortuary — maximum total £1,749.' },
  { q: 'Where will the cremation take place?', a: 'At a local crematorium near the family. We do not centralise — every cremation is delivered by a vetted local independent funeral director, often within 25 miles of home.' },
  { q: 'Will I be able to speak to a real person?', a: 'Yes. We answer 24 hours a day — a real person, every call. The number is 0333 242 1405.' },
  { q: 'What\'s included in the price?', a: 'Collection from a hospital or coroner\'s mortuary, professional care, a simple coffin, all paperwork, the cremation at a local crematorium, and the return of ashes. Priority Care (collection from home, hospice or care home) is an optional £250 add-on.' },
];

const GENERICS: Generic[] = [
  // ====== CHEAP / LOW COST family ======
  {
    slug: 'cheap-direct-cremation',
    title: 'Cheap Direct Cremation UK — From £1,499 All-Inclusive',
    modifier: 'cheap',
    serviceNoun: 'direct cremation',
    intentMatch: 'Transactional, price-sensitive — wants the lowest credible all-in price',
    longForm: [
      pt(`Cheap direct cremation is the lowest-cost UK funeral choice and now accounts for around one in every five UK funerals. A direct cremation removes the formal service at the crematorium, which is what drives most of the cost out of a traditional funeral — but cheap should never mean cutting corners on the care your loved one receives.`),
      pt(`The cheapest credible direct cremation in the UK in 2026 sits around £1,400-£1,500 all-inclusive. Below that, you're typically looking at a centralised operation — one where your loved one is transported to a regional hub and cremated far from home — or a provider with hidden fees that emerge at the point of need.`),
      h2('What is a "cheap" direct cremation, exactly?'),
      pt(`A cheap direct cremation should still include: collection from a hospital or coroner's mortuary, professional care in a mortuary, a simple coffin suitable for cremation, all the legal paperwork, the cremation itself at a local crematorium, and the return of ashes. If a quote excludes any of those items at the headline price, it isn't really an all-in figure.`),
      pt(`Best Direct Cremation costs £1,499 all-inclusive. The only optional cost is the £250 Priority Care collection fee if the person who has died is at home, in a care home, or anywhere outside a hospital. Maximum total £1,749 with Priority Care. There are no other fees added at the point of need.`),
      h2('Cheap vs ultra-cheap — what changes below £1,400'),
      pt(`Several UK providers advertise direct cremation at £950-£1,200. The way they get there is by centralising operations: your loved one is collected by a regional driver and transported to a single mortuary, often hundreds of miles from home, then cremated at one of a small number of owned crematoria. For some families that's acceptable; for many, it is not.`),
      pt(`Other ultra-cheap providers achieve their headline price by treating Priority Care as a paid extra — sometimes £400-£500 — which most families need (most deaths don't happen in a hospital). The headline £950 becomes a real £1,450, which isn't much cheaper than a transparent £1,499.`),
      h2('How to compare cheap direct cremation providers fairly'),
      pt(`Ask every provider four questions: (1) What is your single all-in price including everything except optional add-ons? (2) Where will my loved one be collected from and how far will they be transported? (3) Which crematorium will be used? (4) Are you NAFD or SAIF accredited? Honest providers answer all four directly. Evasive providers tell you what to watch out for.`),
      h2('Why £1,499 is the right price for a proper direct cremation'),
      pt(`£1,499 covers a local independent funeral director's actual cost to deliver a dignified service — their staff, premises, vehicles, mortuary, paperwork and the crematorium fee — plus a fair margin to keep them in business. There is no centralised hub. Your loved one stays close to home, in the care of a real funeral professional whose reputation is in your local community.`),
      pt(`That's the difference between cheap and cheap-but-proper. Best Direct Cremation provides cheap-but-proper.`),
      ...ctaSection('cheap-direct-cremation'),
    ],
    faqs: [
      { q: 'What is the cheapest direct cremation in the UK?', a: 'Credible UK direct cremation providers in 2026 charge £1,400-£1,700 all-inclusive. Anything below £1,200 typically means a centralised operation or hidden fees that emerge at the point of need. Best Direct Cremation costs £1,499 all-inclusive with no hidden extras.' },
      { q: 'Are cheap direct cremations dignified?', a: 'Yes — provided the provider uses a vetted local independent funeral director (not a centralised hub) and is NAFD or SAIF accredited. Cheap should mean lower cost, not lower standards.' },
      ...standardFaqs,
    ],
  },
  {
    slug: 'low-cost-direct-cremation',
    title: 'Low-Cost Direct Cremation UK — Transparent £1,499 Pricing',
    modifier: 'low-cost',
    serviceNoun: 'direct cremation',
    intentMatch: 'Cost-conscious, prefers professional softer language to "cheap"',
    longForm: [
      pt(`Low-cost direct cremation is the affordable alternative to a traditional UK funeral, currently costing £4,510 on average (SunLife Cost of Dying Report 2026). A low-cost direct cremation typically costs £1,400-£1,700 all-inclusive — saving most families more than £3,000.`),
      pt(`Best Direct Cremation costs £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection fee if the person who has died is not at a hospital or coroner's mortuary. Maximum total £1,749.`),
      h2('What "low-cost" should mean'),
      pt(`Low-cost should mean: lower price than a traditional funeral, full transparency on what's included, no surprise extras at the point of need, and the same standards of dignity and care that any family deserves. It should not mean: centralised logistics that transport your loved one hundreds of miles, ultra-cheap headline pricing with add-on fees that double the cost, or unaccredited providers cutting corners on facilities.`),
      h2('What you get for £1,499 with Best Direct Cremation'),
      pt(`Collection from a hospital or coroner's mortuary. Professional care of your loved one in a local independent funeral director's mortuary. A simple coffin suitable for cremation. All legal paperwork including the doctor's certificates and the Green Form. The cremation itself at a local crematorium. The return of ashes to you or scattering at the crematorium. All of it delivered by a NAFD- or SAIF-accredited local independent funeral director — never centralised.`),
      h2('Comparing low-cost direct cremation providers'),
      pt(`Most major UK direct cremation providers now sit in the £1,400-£2,200 range. Pure Cremation, the largest dedicated direct cremation operator, charges around £1,950 for their direct cremation plan and uses a centralised model where your loved one may be transported to their Andover mortuary regardless of where you live. Co-op Funeralcare charges around £1,995 for direct cremation through their own branch network. Best Direct Cremation charges £1,499 through a local independent funeral director network — the lowest credible price for genuinely local delivery.`),
      h2('The hidden costs to watch for'),
      pt(`The most common hidden cost in low-cost direct cremation is the Priority Care or out-of-hours collection fee. If someone dies at home or in a care home, they need to be collected promptly because there are no mortuary facilities. Some providers advertise a low headline price (£950-£1,200) but then charge £400-£500 when Priority Care is needed. Always confirm the all-in price including Priority Care before signing up. Best Direct Cremation's Priority Care fee is £250, taking the maximum total to £1,749 — fully disclosed before you commit.`),
      ...ctaSection('low-cost-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'affordable-direct-cremation',
    title: 'Affordable Direct Cremation UK — £1,499 All-Inclusive',
    modifier: 'affordable',
    serviceNoun: 'direct cremation',
    intentMatch: 'Affordable framing — accessible language for older searchers',
    longForm: [
      pt(`An affordable direct cremation in the UK in 2026 costs around £1,400-£1,700 all-inclusive — roughly a third of the cost of a traditional funeral (£4,510 average, SunLife Cost of Dying Report 2026). Best Direct Cremation is £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection fee for non-hospital collections.`),
      h2('Affordable doesn\'t mean compromising on care'),
      pt(`Affordable direct cremation makes a funeral accessible to families who would otherwise be forced into difficult financial decisions during the worst possible time. But affordable shouldn't mean cutting corners on the dignity and care your loved one receives. The right provider keeps the price low by removing the formal ceremony at the crematorium — not by centralising operations or cutting corners on professional care.`),
      h2('What an affordable direct cremation includes'),
      pt(`A proper affordable direct cremation includes: collection of the deceased, professional care in a local mortuary, a simple coffin suitable for cremation, all paperwork, the cremation at a local crematorium, and the return of ashes. Best Direct Cremation includes all of this for £1,499.`),
      h2('Why our pricing works'),
      pt(`We deliver every direct cremation through a network of vetted local independent funeral directors who already have premises, vehicles, mortuaries and trained staff in their community. We don't run centralised mortuaries or own crematoria. The £1,499 covers the local funeral director's full cost plus a fair margin, with no hidden centralised overhead and no surprise fees added at the point of need.`),
      h2('Help if you genuinely can\'t afford a funeral'),
      pt(`If even £1,499 is out of reach, three options are worth knowing about. The Funeral Expenses Payment from the DWP can cover £1,000+ towards costs for people on certain benefits (Universal Credit, Pension Credit, Housing Benefit, etc.). The Children's Funeral Fund covers most fees if a child under 18 has died. As a last resort, a Public Health Funeral arranged by the local council provides a basic, dignified service at no cost to the family.`),
      ...ctaSection('affordable-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== NO SERVICE / UNATTENDED family ======
  {
    slug: 'no-service-cremation',
    title: 'No Service Cremation UK — What It Means',
    modifier: 'no-service',
    serviceNoun: 'cremation',
    intentMatch: 'Researching the unattended cremation concept',
    longForm: [
      pt(`A no-service cremation — also known as direct cremation or unattended cremation — is a cremation without a formal service or ceremony at the crematorium. No family present, no celebrant, no music, no flowers. The deceased is collected, cared for, and cremated, and the ashes are returned to the family.`),
      pt(`No-service cremations have grown rapidly in the UK and now account for around one in every five funerals. Families choose them for many reasons: cost (typically £1,400-£1,700 instead of £4,510 for a traditional funeral), simplicity, the freedom to arrange their own personal memorial separately, or because the deceased specifically asked for one in their will.`),
      h2('What "no service" actually means'),
      pt(`No service means there is no ceremony at the crematorium — no chapel booking, no celebrant or minister, no procession, no committal service. The cremation itself is still dignified and carried out to the same professional standards as any other cremation. The difference is purely in the ceremonial element around it.`),
      pt(`Many families who choose a no-service cremation then hold their own memorial or celebration of life separately — at home, in a pub, at a favourite outdoor location, or somewhere that holds special meaning. Some do nothing formal at all and remember their loved one quietly. There is no right or wrong way.`),
      h2('What still happens with a no-service cremation'),
      pt(`Your loved one is still collected from the place of death by a professional funeral director. They are still cared for with dignity in a proper mortuary. The legal paperwork (including the doctor's cremation certificates and the registrar's Green Form) is still completed. The cremation is still carried out by a qualified crematorium operator. The ashes are still returned to you, in an urn or scatter tube. Everything that needs to happen with dignity, still happens.`),
      h2('Who chooses a no-service cremation'),
      pt(`People who want simplicity. People who want to spare their family the cost and stress of arranging a formal funeral. People who'd rather their family hold a personal memorial later, in a meaningful place, than be confined to a 25-minute crematorium service. People for whom the formal service isn't culturally or personally important. And increasingly, people who simply prefer the modern, lower-cost approach.`),
      h2('What it costs'),
      pt(`A no-service cremation in the UK in 2026 typically costs £1,400-£1,700 all-inclusive. Best Direct Cremation charges £1,499, with the only optional cost being a £250 Priority Care collection fee for non-hospital collections. The cost saving versus a traditional funeral is typically £3,000 or more — money that can go towards a personal memorial later, the wake, or simply remain in the family.`),
      ...ctaSection('no-service-cremation'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'unattended-cremation',
    title: 'Unattended Cremation UK — Costs, Process and What to Expect',
    modifier: 'unattended',
    serviceNoun: 'cremation',
    intentMatch: 'Researching what unattended cremation means',
    longForm: [
      pt(`An unattended cremation is a cremation that takes place without family or friends present at the crematorium. It is the same thing as a direct cremation or no-service cremation — three terms for the same service, used interchangeably across the UK funeral industry.`),
      pt(`Unattended cremations have become the fastest-growing UK funeral type. Around one in every five UK funerals is now unattended, driven by families wanting lower cost, simpler arrangements, and the freedom to organise a personal memorial on their own terms.`),
      h2('Why "unattended"?'),
      pt(`The "unattended" part is the key feature — and the reason the service is so much cheaper than a traditional funeral. Without family or friends at the crematorium, there's no need for: a chapel booking (typically £500-£1,000), a celebrant or minister (£200-£400), printed orders of service, music licensing, hearses and limousines for family, professional pallbearers, or flowers at the crematorium. All of these costs are stripped out.`),
      pt(`What remains is the dignified core of the funeral: the collection of your loved one, their professional care, the cremation itself, and the return of ashes.`),
      h2('What unattended cremation costs'),
      pt(`UK unattended cremation prices in 2026 typically range from £1,400 to £2,200. Best Direct Cremation charges £1,499 all-inclusive with no hidden extras (Priority Care is an optional £250 add-on for non-hospital collections, taking the maximum to £1,749).`),
      h2('The unattended cremation process'),
      pt(`Step 1: Call us on 0333 242 1405 — a real person answers, 24 hours a day. Step 2: A local funeral director collects your loved one from the place of death. Step 3: They are cared for in the local funeral director's mortuary while paperwork is completed. Step 4: On the appointed day, the funeral director takes your loved one to a local crematorium, where the cremation takes place. Step 5: The ashes are returned to you within 5-14 days. The whole process typically takes 2-3 weeks from death to ashes returned.`),
      h2('Can family see their loved one before the cremation?'),
      pt(`Yes, in most cases. While the cremation itself is unattended, many families ask to spend a few moments with their loved one at the funeral director's premises before they leave for the crematorium. This is usually possible if requested in advance. Some families find this much more meaningful than a formal crematorium service.`),
      h2('After the cremation'),
      pt(`Your local funeral director returns the ashes to you (or can scatter them at the crematorium garden of remembrance if you prefer). Most families then hold a personal memorial later — at home, outdoors, in a venue that means something. This is the great strength of unattended cremation: it separates the practicalities (the cremation) from the personal (the memorial), letting families plan something genuinely meaningful in their own time.`),
      ...ctaSection('unattended-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== "SIMPLE" / "CHEAP CREMATION" family ======
  {
    slug: 'simple-cremation-uk',
    title: 'Simple Cremation UK — What It Means and What It Costs',
    modifier: 'simple',
    serviceNoun: 'cremation',
    intentMatch: 'Researching the simple cremation concept',
    longForm: [
      pt(`A simple cremation in the UK is the most affordable funeral option, removing the formal ceremony at the crematorium while keeping the dignified care your loved one deserves. The phrase "simple cremation" is sometimes used interchangeably with "direct cremation" — and sometimes used by traditional funeral directors (notably Co-op Funeralcare and Dignity) for their lowest-tier attended cremation plans.`),
      h2('Simple cremation = direct cremation (most often)'),
      pt(`When someone uses the phrase "simple cremation" in 2026, they almost always mean direct cremation: a dignified cremation without a service at the crematorium, with the ashes returned to the family. This is the option costing around £1,400-£1,700 in the UK and accounting for around one in every five UK funerals.`),
      h2('Simple cremation as marketing name'),
      pt(`Some traditional funeral directors call their lowest-tier attended cremation a "simple cremation". These typically include a brief 20-30 minute service at the crematorium with family present and cost around £2,500-£3,500. They are not the same as a direct or unattended cremation — they include the chapel booking and a celebrant.`),
      pt(`Always ask the provider exactly what is included. If you want the lowest possible cost and don't need or want a service at the crematorium, you want a direct or unattended cremation. If you want a brief moment of family gathering at the crematorium, you want a simple (attended) cremation.`),
      h2('What Best Direct Cremation offers'),
      pt(`Best Direct Cremation provides direct cremation — the simplest, most affordable option. £1,499 all-inclusive, delivered locally by a vetted independent funeral director. The £250 Priority Care add-on covers non-hospital collections, taking the maximum to £1,749. No service at the crematorium; full dignity and care throughout.`),
      h2('When simple is the right choice'),
      pt(`Simple cremation is right when: the deceased asked for the simplest possible send-off; the family wants to spare itself the cost and stress of a formal funeral; the family plans to hold a personal memorial separately and doesn't need a crematorium service to mark the cremation itself; cost is a meaningful factor in the decision; or the family simply prefers a modern, low-key approach.`),
      ...ctaSection('simple-cremation-uk'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'cheap-cremation',
    title: 'Cheap Cremation UK — What\'s Actually Available?',
    modifier: 'cheap',
    serviceNoun: 'cremation',
    intentMatch: 'Researching cheapest possible cremation',
    longForm: [
      pt(`Cheap cremation in the UK in 2026 means direct cremation — a cremation without a formal service at the crematorium. Direct cremation typically costs £1,400-£1,700 all-inclusive, around two-thirds less than the £4,510 average UK funeral (SunLife Cost of Dying Report 2026).`),
      pt(`Best Direct Cremation charges £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection fee for non-hospital collections — maximum total £1,749.`),
      h2('The cheapest credible option'),
      pt(`The genuinely cheapest UK funeral options are: a direct cremation (£1,400-£1,700) which most families pay for; a Funeral Expenses Payment from the DWP (£1,000+) for low-income families; or a Public Health Funeral arranged by the council at no cost to the family. Each suits different circumstances.`),
      h2('How direct cremation gets the price so low'),
      pt(`Direct cremation removes everything ceremonial: no chapel service, no celebrant, no hearse and limousines, no flowers, no embalming, no upgraded coffin. What remains is the essential, dignified care of the deceased — collection, mortuary care, cremation, ashes returned. The cost saving versus a traditional funeral is enormous: typically £3,000+.`),
      h2('Why some providers are even cheaper'),
      pt(`A few providers advertise direct cremation at £950-£1,200. The trade-off is centralisation: your loved one is collected by a regional driver and may be transported hundreds of miles to a central mortuary, then cremated at one of a small number of owned crematoria. For some families that's acceptable; for many, keeping their loved one close to home matters. Best Direct Cremation costs £1,499 for genuinely local delivery — your loved one stays close to home, in the care of a local independent funeral director.`),
      h2('Beware hidden fees'),
      pt(`The most common hidden fee in cheap cremation is the Priority Care or out-of-hours collection. If someone dies at home or in a care home (which most people do), the body must be collected promptly. Some providers advertise £950-£1,200 but charge £400-£500 for Priority Care — making the real cost similar to a transparent £1,499. Always confirm the all-in price including Priority Care before signing up.`),
      ...ctaSection('cheap-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== INFORMATIONAL / DECISION family ======
  {
    slug: 'direct-cremation-explained',
    title: 'Direct Cremation Explained — A Plain-English Guide',
    modifier: 'explained',
    serviceNoun: 'direct cremation',
    intentMatch: 'Informational — wants to understand what direct cremation is',
    longForm: [
      pt(`Direct cremation is the simplest, most affordable type of UK funeral. It removes the formal service at the crematorium, focusing instead on the dignified core of the funeral: the collection of your loved one, professional care, the cremation itself, and the return of ashes.`),
      pt(`Around one in every five UK funerals is now a direct cremation. The reasons families choose it are simple — lower cost, simpler arrangements, and the freedom to remember their loved one their own way in their own time.`),
      h2('What direct cremation includes'),
      pt(`Collection of the deceased (usually 24/7), professional care in a mortuary, a simple coffin suitable for cremation, all legal paperwork (the doctor's certificates and the registrar's Green Form), the cremation itself at a local crematorium, and the return of ashes to the family (or scattering at the crematorium garden of remembrance if preferred).`),
      h2('What direct cremation does not include'),
      pt(`A service or ceremony at the crematorium. Attendance by family or friends at the cremation. A hearse or limousine for family transport. A celebrant or minister. Music or readings. Flowers. An upgraded coffin. Embalming. Memorial arrangements. Formal notices. Alternative urns.`),
      h2('Why families choose it'),
      pt(`Cost is one reason: a direct cremation costs £1,400-£1,700 in the UK in 2026, compared to £4,510 for the average UK funeral. But families also choose direct cremation because they want simplicity, because the deceased specifically asked for it in their will, because they want to spare their family the cost and stress, or because they plan to hold a personal memorial separately.`),
      h2('Who Best Direct Cremation is for'),
      pt(`Best Direct Cremation is for families who want a low-cost direct cremation delivered locally — by a vetted independent funeral director in their community, not by a centralised national hub. Our £1,499 all-inclusive price reflects the actual cost of a proper local service plus a fair margin, with no hidden extras and no compromise on dignity.`),
      h2('What happens after the cremation'),
      pt(`Direct cremation gives families the freedom to remember their loved one their own way. Some hold a memorial service weeks or months later — at home, at a favourite venue, somewhere meaningful. Others scatter ashes at a special place. Some keep ashes at home. Some commission memorial jewellery. There is no right or wrong way and no time pressure to decide.`),
      ...ctaSection('direct-cremation-explained'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'is-direct-cremation-right-for-me',
    title: 'Is Direct Cremation Right for Me?',
    modifier: 'is-it-right',
    serviceNoun: 'direct cremation',
    intentMatch: 'Decision-stage — weighing direct cremation vs alternatives',
    longForm: [
      pt(`Direct cremation isn't right for every family. It's a different kind of funeral — simpler, lower-cost, more flexible — and like all funeral choices, it's deeply personal. This guide helps you decide whether direct cremation is right for you and the person who has died.`),
      h2('Direct cremation is probably right if...'),
      pt(`You or the deceased prefer simplicity over ceremony. The financial cost of a traditional funeral matters. You want to hold a personal memorial later, in a venue and at a time that means something to your family, rather than being confined to a 25-minute crematorium service. The deceased specifically asked for "the simplest possible funeral" or "no fuss" — direct cremation matches that wish. Religious or cultural tradition doesn't require a specific funeral form.`),
      h2('Direct cremation is probably not right if...'),
      pt(`You or the deceased want a religious service led by a minister of your faith — for most religious families, an attended funeral suits better. You feel strongly that family should be present at the moment of cremation — this is the defining feature of an attended cremation. The deceased's religious tradition specifically requires a burial (e.g. Muslim or Jewish tradition). You want a hearse-led procession or formal ceremonial elements.`),
      h2('Direct cremation might be right if...'),
      pt(`You're caught between options. Many families find a hybrid approach works well: a direct cremation followed by a personal memorial later. The direct cremation handles the practicalities at low cost; the memorial — whenever and wherever the family is ready — provides the personal, meaningful gathering. This combination is increasingly popular and often more emotionally satisfying than a formal crematorium service.`),
      h2('What we hear from families who chose direct cremation'),
      pt(`The most common reflection from families who chose direct cremation is that they wished they had known it was an option sooner. Many traditional funeral directors don't volunteer direct cremation as a choice — and many families assume a "proper" funeral has to mean an expensive, formal ceremony at the crematorium. Direct cremation is a proper funeral. Just different.`),
      h2('The hybrid approach: direct cremation + memorial'),
      pt(`For many UK families now, the right answer is a direct cremation through a provider like Best Direct Cremation, followed by a personal memorial weeks or months later. The direct cremation costs £1,499 all-inclusive. The memorial can be held at home, in a pub, on a beach, at a community hall — anywhere that matters. You can use a celebrant if you want one. You can play any music, share any stories, take all the time you need.`),
      ...ctaSection('is-direct-cremation-right-for-me'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'fast-cremation',
    title: 'Fast Cremation UK — How Quickly Can It Be Arranged?',
    modifier: 'fast',
    serviceNoun: 'cremation',
    intentMatch: 'Urgency-driven — needs to arrange cremation quickly',
    longForm: [
      pt(`In the UK, a cremation can typically be arranged within 1-2 weeks of death. The main constraints are the legal paperwork (which takes 1-3 working days) and the crematorium's available slots. Direct cremation is often slightly faster than an attended cremation because there's no need to coordinate a service date with family.`),
      h2('Timeline from death to cremation'),
      pt(`Day 1: Death occurs. If at home, GP or hospice contacts the family; if in hospital, paperwork begins immediately. Day 2-3: Death registered at the local register office (within 5 days legally required in England, Wales and NI; 8 in Scotland). Day 3-5: Funeral director obtains the necessary cremation paperwork from the doctor or coroner. Day 5-14: Crematorium slot is booked and the cremation takes place. Day 14-21: Ashes returned to the family.`),
      h2('Why fastest isn\'t always best'),
      pt(`Rushing a funeral often leaves families regretting they didn't have time to gather and grieve properly. While direct cremation is faster than a traditional funeral, "fast" should usually mean "without unnecessary delay" rather than "as quickly as possible". Most families benefit from 1-2 weeks to register the death, contact family, and process the shock.`),
      h2('When speed genuinely matters'),
      pt(`Some situations do require speed: religious requirements (some faiths require cremation or burial within hours or days); a family member travelling from abroad who needs the cremation to happen before they arrive or before they have to leave; a coroner's investigation that has been completed and there's no remaining reason to wait. In all these cases, talk to the funeral director — they'll tell you honestly what's possible.`),
      h2('How Best Direct Cremation handles urgent requests'),
      pt(`Call us on 0333 242 1405 — a real person answers, 24 hours a day. We'll connect you with a local funeral director who can typically begin collection the same day. The legal paperwork takes 2-3 working days regardless of provider. The fastest realistic timeline from death to cremation is around 5-7 working days for most families.`),
      ...ctaSection('fast-cremation'),
    ],
    faqs: standardFaqs,
  },

  // ====== "DIRECT CREMATION" comparison / context ======
  {
    slug: 'direct-cremation-vs-traditional',
    title: 'Direct Cremation vs Traditional Funeral — Detailed Comparison',
    modifier: 'comparison',
    serviceNoun: 'direct cremation',
    intentMatch: 'Comparison shoppers',
    longForm: [
      pt(`Direct cremation and traditional funerals are increasingly the two ends of the UK funeral spectrum. Around 20% of UK funerals are now direct cremations; around 75% are still traditional cremations or burials with a ceremonial element. This guide compares them on every dimension that matters.`),
      h2('Cost'),
      pt(`Direct cremation: £1,400-£1,700 in 2026. Traditional cremation: £4,510 average (SunLife Cost of Dying Report 2026), with the more elaborate end running to £5,500+. Traditional burial: £5,000-£10,000+ depending on the plot cost. The cost difference is the single biggest driver of direct cremation's growth — direct cremation saves families around £3,000 versus a traditional cremation.`),
      h2('Ceremony'),
      pt(`Traditional: 20-30 minute crematorium service led by a celebrant or minister, with music, readings, hymns, and a committal. Family and friends attend. Direct: no ceremony at the crematorium. Family can hold a personal memorial separately if they wish — many do, on their own terms.`),
      h2('Timing'),
      pt(`Traditional cremation: typically 2-3 weeks from death to funeral, longer if a celebrant or specific crematorium slot is needed. Direct cremation: typically 1-2 weeks. Both allow time for family to gather and register the death.`),
      h2("What's included"),
      pt(`Traditional: collection, care, embalming if requested, premium coffin choice, hearse and limousines, celebrant, crematorium service, music licensing, full floral tributes, order of service printing, ashes returned. Direct: collection, care, simple coffin, paperwork, cremation, ashes returned. Everything ceremonial is removed.`),
      h2('Who attends'),
      pt(`Traditional: family, close friends, sometimes wider community. The funeral is a focal point for collective grieving. Direct: no one attends the cremation itself. The family may still hold a personal memorial later that anyone can attend.`),
      h2('Which is right for you?'),
      pt(`Traditional suits families who want the structured ceremony, the public gathering, the formal goodbye at the moment of cremation. Direct suits families who prefer simplicity, want to keep costs down, want flexibility to memorialise later, or know the deceased specifically wanted a simpler send-off. Many families now combine: direct cremation for the practicalities + a personal memorial later for the gathering.`),
      h2('A hybrid approach is increasingly popular'),
      pt(`Around half of UK families who choose direct cremation now hold a separate memorial service afterwards. The direct cremation costs £1,499 with Best Direct Cremation. The memorial can be at home, in a pub, on a beach, in a community hall — anywhere. This combination provides both the cost savings of direct cremation AND the personal gathering many families need to grieve properly.`),
      ...ctaSection('direct-cremation-vs-traditional'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'direct-cremation-vs-attended-cremation',
    title: 'Direct Cremation vs Attended Cremation — How They Differ',
    modifier: 'comparison',
    serviceNoun: 'direct cremation',
    intentMatch: 'Comparison — choosing between direct and attended',
    longForm: [
      pt(`Direct cremation and attended cremation are the two main types of UK cremation funeral. Direct cremation has no service at the crematorium and costs £1,400-£1,700 in 2026. Attended cremation has a brief 20-30 minute service at the crematorium with family present, and costs £2,500-£3,800. This guide explains the differences in detail.`),
      h2('The defining difference'),
      pt(`Attended cremation = family is at the crematorium for a brief service. Direct cremation = no one attends at the crematorium; the family memorialises separately if at all. Everything else flows from this.`),
      h2('What attended cremation includes that direct doesn\'t'),
      pt(`A booked crematorium chapel slot (typically £500-£1,000 in the fee). A celebrant or minister to lead the service (typically £200-£400). Music licensing for any songs played. Often a hearse with the family following. Time for committal — the brief moment when the coffin is moved behind the curtain or onto the catafalque. An order of service printed for attendees.`),
      h2('What\'s the same'),
      pt(`Both involve: dignified collection of the deceased; professional care in a mortuary; a simple-to-mid-range coffin; the legal paperwork; the cremation itself at a crematorium; the return of ashes. The deceased is treated with exactly the same standards of care in both cases.`),
      h2('Cost comparison'),
      pt(`Direct cremation: £1,400-£1,700 (Best Direct Cremation £1,499). Attended cremation: £2,500-£3,800 depending on provider, coffin choice, celebrant fee. The cost difference is around £1,000-£2,000 — significant but smaller than the difference between direct cremation and a fully traditional funeral.`),
      h2('Which is right for which family'),
      pt(`Attended cremation suits families who want a brief moment of gathering at the crematorium — a formal goodbye in a familiar funeral setting — but who don't need or want the full traditional funeral with limousines, large floral tributes, and an extended service. Direct cremation suits families who don't want or need a crematorium service at all — typically because they plan to hold a personal memorial later, or because the deceased specifically asked for the simplest possible send-off.`),
      h2('Best Direct Cremation focuses on direct'),
      pt(`Best Direct Cremation specialises in direct cremation. We don't currently offer attended cremation — for that, you would need a traditional funeral director (we recommend asking your local NAFD or SAIF members). But if direct cremation is right for your family, we offer it at £1,499 all-inclusive, delivered by a vetted local independent funeral director.`),
      ...ctaSection('direct-cremation-vs-attended-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== NEAR ME / LOCAL family ======
  {
    slug: 'direct-cremation-near-me',
    title: 'Direct Cremation Near Me — Local Direct Cremation Across the UK',
    modifier: 'near-me',
    serviceNoun: 'direct cremation',
    intentMatch: 'Local search — "near me"',
    longForm: [
      pt(`When you search "direct cremation near me", you almost certainly want a service delivered by a funeral director close to your home — not by a centralised national operation that transports your loved one hundreds of miles for the cremation. This guide explains how to find a genuinely local direct cremation provider.`),
      h2('Why local matters'),
      pt(`Many UK direct cremation providers operate centralised models. Their collection drivers are based at regional hubs. Their mortuary is in one location (Pure Cremation's is in Andover, Hampshire). Their cremations take place at one of a small number of crematoria they own or have agreements with. This keeps their costs low at scale but means your loved one may be transported a significant distance from home — and the cremation may take place far from anywhere meaningful to you.`),
      pt(`A local direct cremation, delivered by a vetted independent funeral director in your community, keeps your loved one close to home throughout. The funeral director's mortuary is local. The cremation is at a local crematorium. The professional caring for your loved one is someone whose reputation is in your community.`),
      h2('How Best Direct Cremation works locally'),
      pt(`Best Direct Cremation operates the local model by design. Every cremation we arrange is delivered by a vetted local independent funeral director — one we have personally checked for facilities, accreditation (NAFD or SAIF), staff training and standards of care. There is no central mortuary, no transporting your loved one to a regional hub.`),
      pt(`Our network covers every county in England and Wales. We're expanding into Scotland and Northern Ireland. When you call us on 0333 242 1405, we'll match you with a local funeral director near where you live — typically within 10-15 miles of your home.`),
      h2('What "near me" really means'),
      pt(`For most UK direct cremation needs, "near me" means: a funeral director with their own premises within 10-25 miles; a mortuary within the same distance; a crematorium within 10-15 miles of your home (the funeral director typically picks the closest available); and a real person you can speak to who knows the area.`),
      h2('Coverage check'),
      pt(`We cover every county in England and Wales through our partner FD network. Some specific towns may be served by a partner in the next town over (5-10 miles), which is perfectly acceptable for direct cremation collection. Call 0333 242 1405 and we'll confirm coverage for your exact area immediately.`),
      ...ctaSection('direct-cremation-near-me'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'best-direct-cremation-providers-uk',
    title: 'Best Direct Cremation Providers UK 2026',
    modifier: 'best',
    serviceNoun: 'direct cremation providers',
    intentMatch: 'Comparison shoppers researching providers',
    longForm: [
      pt(`The UK direct cremation market in 2026 is dominated by a handful of providers: Pure Cremation (the largest dedicated direct cremation operator), Co-op Funeralcare and Dignity (national funeral brands offering direct cremation as one of their services), and a growing number of independent and local providers including Best Direct Cremation. This guide is a fair, factual comparison.`),
      h2('Pure Cremation'),
      pt(`Direct cremation price: ~£1,950. Model: centralised. Pure Cremation operates a single mortuary in Andover, Hampshire, and a network of owned crematoria. Your loved one may be transported a significant distance from home. FCA-authorised (since 2022) for their funeral plans. Largest dedicated direct cremation operator in the UK by volume.`),
      h2('Co-op Funeralcare'),
      pt(`Direct cremation price: ~£1,995. Model: own branch network. Co-op uses its own funeral directors across the UK. Cremation typically at a local crematorium (Co-op doesn't own its own). FCA-authorised for funeral plans. Strong brand trust through the Co-operative Group.`),
      h2('Dignity'),
      pt(`Direct cremation price: ~£2,200. Model: own funeral directors + own crematoria. Dignity owns approximately 45+ crematoria across the UK, so cremation often takes place at one of their own facilities. FCA-authorised. Recently restructured (delisted from the London Stock Exchange in 2023) — verify current corporate entity on the FCA Register.`),
      h2('Golden Charter (Network)'),
      pt(`Direct cremation price: ~£1,700-£2,200 depending on local FD. Model: independent FD network. Golden Charter administers plans centrally but delivers through ~3,000 independent funeral directors across the UK. Local FD does the actual work. FCA-authorised. Strong choice for those wanting a local FD.`),
      h2('Avalon'),
      pt(`Direct cremation price: ~£1,800-£2,200. Model: independent FD network through the Avalon Trust. Similar to Golden Charter but smaller network. FCA-authorised. Verify the specific local FD before committing.`),
      h2('Best Direct Cremation'),
      pt(`Direct cremation price: £1,499 all-inclusive (£250 optional Priority Care; maximum £1,749). Model: vetted local independent FD network. Every cremation delivered by a NAFD- or SAIF-accredited local independent funeral director. No centralised mortuary or hub transport. Best price in the UK for genuinely local direct cremation delivery.`),
      h2('How to choose'),
      pt(`Decide what matters most: lowest price (Best Direct Cremation), brand trust (Co-op or Age Co), local delivery (Best Direct Cremation, Golden Charter, Avalon), or specific crematorium ownership (Dignity, Pure Cremation). Then verify FCA authorisation for any funeral plan provider on the FCA Register.`),
      ...ctaSection('best-direct-cremation-providers-uk'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'direct-cremation-companies-uk',
    title: 'UK Direct Cremation Companies — Full Provider List',
    modifier: 'directory',
    serviceNoun: 'direct cremation companies',
    intentMatch: 'Directory-style; wants a full list',
    longForm: [
      pt(`The UK direct cremation market has grown rapidly since 2018, with dozens of providers now competing on price, model, and service quality. This guide lists the major UK direct cremation companies in 2026 and explains how to evaluate them.`),
      h2('National direct cremation specialists'),
      pt(`Pure Cremation, Aura, Simplicity Cremations, Cremation Direct, Memoria. All operate centralised or semi-centralised models. Typical price range £1,200-£2,200. Largest by volume: Pure Cremation.`),
      h2('National funeral chains offering direct cremation'),
      pt(`Co-op Funeralcare, Dignity, Funeral Partners. All offer direct cremation alongside traditional services. Typical price range £1,800-£2,500. Strong brand recognition.`),
      h2('Local-FD network operators'),
      pt(`Best Direct Cremation (£1,499), Golden Charter network, Avalon network. All deliver via local independent funeral directors. Typical price range £1,499-£2,200. Best choice for genuinely local delivery.`),
      h2('Independent local providers'),
      pt(`Thousands of local independent funeral directors offer direct cremation alongside their traditional services. Prices vary widely (£1,400-£2,800 typically). NAFD or SAIF accreditation is the baseline trust signal.`),
      h2('How to compare'),
      pt(`Always ask: (1) what is the single all-in price? (2) Where will collection happen and how far will my loved one be transported? (3) Which crematorium will be used? (4) Are you NAFD or SAIF accredited? Honest providers answer all four directly.`),
      h2('Watch for hidden fees'),
      pt(`Priority Care fees, out-of-hours collection charges, mileage charges over a certain distance, doctor's certificate fees not included in the headline. Confirm the all-in price including Priority Care before signing up.`),
      ...ctaSection('direct-cremation-companies-uk'),
    ],
    faqs: standardFaqs,
  },
  // ====== "AT HOME" / "QUICKLY" family ======
  {
    slug: 'cremation-when-someone-dies-at-home',
    title: 'Cremation When Someone Dies at Home — Your Steps',
    modifier: 'at-home',
    serviceNoun: 'cremation',
    intentMatch: 'Practical — someone has died at home',
    longForm: [
      pt(`When someone dies at home in the UK, the immediate practical steps depend on whether the death was expected or unexpected. Either way, a direct cremation is the simplest, lowest-cost funeral choice — and arranging it from home is straightforward.`),
      h2('Step 1 — Was the death expected or unexpected?'),
      pt(`If expected (someone with a terminal illness under hospice or GP care): call the GP surgery or community nursing team. A doctor will attend to verify the death. There is no rush — give yourself a few minutes with your loved one before you make calls.`),
      pt(`If unexpected: call 999. Paramedics will attend, verify the death, and involve the police and coroner if needed. Do not move the person.`),
      h2('Step 2 — Call a funeral director'),
      pt(`Call Best Direct Cremation on 0333 242 1405 — a real person answers, 24 hours a day. We'll dispatch a local funeral director to collect your loved one. Because the death is at home (not in a hospital), this is a Priority Care collection — an optional £250 add-on to the £1,499 base price, taking the maximum to £1,749.`),
      h2('Step 3 — Collection'),
      pt(`The collection is dignified and professional. Two trained staff in dark, plain vehicles. No branded vans, no flashing lights. Your loved one is moved into the local funeral director's mortuary nearby — close to home.`),
      h2('Step 4 — Registering the death'),
      pt(`Register the death at the local register office within 5 days (8 in Scotland). You'll need the Medical Certificate of Cause of Death from the doctor. The registrar issues the Death Certificate and the Green Form (cremation certificate) that goes to the funeral director.`),
      h2('Step 5 — The cremation'),
      pt(`Your funeral director handles all the cremation paperwork and books the cremation at a local crematorium, typically 1-2 weeks after death. The cremation itself takes 1-2 hours. There is no service — direct cremation is unattended.`),
      h2('Step 6 — Ashes returned'),
      pt(`Within 5-14 days of the cremation, your loved one's ashes are returned to you in a simple urn or scatter tube. You can hold a personal memorial whenever your family is ready — at home, outdoors, in a venue that means something. No time pressure.`),
      ...ctaSection('cremation-when-someone-dies-at-home'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'cremation-when-someone-dies-in-hospital',
    title: 'Cremation When Someone Dies in Hospital',
    modifier: 'in-hospital',
    serviceNoun: 'cremation',
    intentMatch: 'Practical — someone has died in hospital',
    longForm: [
      pt(`When someone dies in hospital, the immediate practicalities are largely handled by hospital staff. The Medical Certificate of Cause of Death is issued by the doctor who attended your loved one. Your loved one is moved to the hospital mortuary where they can be cared for safely until collection.`),
      h2('You do not need to rush'),
      pt(`Many families feel pressure to make funeral arrangements within hours. You don't need to. The hospital mortuary is a proper facility designed for this — your loved one is cared for with dignity until you've had time to make decisions calmly.`),
      h2('Choosing a funeral director'),
      pt(`Hospitals must allow you to choose any funeral director. The hospital bereavement office can give you a list of local options but is not allowed to recommend or steer you. Take your time. Compare prices. Look for NAFD or SAIF accreditation. Best Direct Cremation costs £1,499 all-inclusive — and crucially, because collection is from a hospital mortuary, there is no Priority Care fee, so the total is £1,499.`),
      h2('What happens next'),
      pt(`Once you appoint a funeral director, they collect your loved one from the hospital mortuary during normal working hours. Your loved one is moved to the local funeral director's mortuary. The funeral director handles all the paperwork. You register the death at the local register office. The cremation takes place 1-2 weeks later. The ashes are returned within 5-14 days of the cremation.`),
      h2('The hospital bereavement office'),
      pt(`Every UK hospital has a bereavement office (or equivalent) that supports families through the immediate practicalities. They issue the Medical Certificate, explain registration, and answer general questions. They do not arrange funerals or recommend specific providers.`),
      h2('Hospital deaths and the coroner'),
      pt(`Roughly 40% of UK hospital deaths are reported to the coroner — typically those that are sudden, unexpected, related to an injury or operation, or where the cause of death isn't immediately clear. If your loved one is referred to the coroner, the cremation paperwork is different (Form Cremation 6 from the coroner replaces the doctor's certificates). The hospital bereavement office and the funeral director both handle this routinely.`),
      ...ctaSection('cremation-when-someone-dies-in-hospital'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'cremation-when-someone-dies-in-care-home',
    title: 'Cremation When Someone Dies in a Care Home',
    modifier: 'in-care-home',
    serviceNoun: 'cremation',
    intentMatch: 'Practical — someone has died in a care home',
    longForm: [
      pt(`When someone dies in a UK care home, the practicalities sit between a hospital death and a death at home. Care homes don't have mortuary facilities, so collection by a funeral director is typically required within a few hours.`),
      h2('Step 1 — The care home contacts the doctor'),
      pt(`The care home will call the GP who looked after your loved one. The GP attends to verify the death and issues the Medical Certificate of Cause of Death. If the death was unexpected or the GP can't issue the certificate, the case may be referred to the coroner.`),
      h2('Step 2 — The care home calls the family'),
      pt(`The care home will call the next of kin (or whoever is the listed contact). At this point you should be given time to come to the care home if you wish. There's no immediate rush to arrange the funeral.`),
      h2('Step 3 — Funeral director collection'),
      pt(`Because care homes don't have mortuary facilities, the funeral director needs to collect your loved one within a few hours. Call Best Direct Cremation on 0333 242 1405 — a real person answers, 24 hours a day. We'll dispatch a local funeral director to attend the care home, typically within 4-12 hours. This is a Priority Care collection — an optional £250 add-on taking the total to £1,749.`),
      h2('Step 4 — Care and paperwork'),
      pt(`Your loved one is moved to the local funeral director's mortuary. The funeral director handles all the cremation paperwork. You register the death at the local register office within 5 days.`),
      h2('Step 5 — The cremation'),
      pt(`The cremation takes place at a local crematorium 1-2 weeks after death. Direct cremation is unattended. Ashes are returned to you within 5-14 days.`),
      h2('Working with the care home'),
      pt(`Most UK care homes have good working relationships with local funeral directors and know the practicalities well. They will often offer to call a specific funeral director on your behalf. You are not obliged to use any specific provider — you have free choice. Best Direct Cremation works with care homes across the UK and can attend any UK care home location.`),
      ...ctaSection('cremation-when-someone-dies-in-care-home'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'cremation-when-someone-dies-in-hospice',
    title: 'Cremation When Someone Dies in a Hospice',
    modifier: 'in-hospice',
    serviceNoun: 'cremation',
    intentMatch: 'Practical — someone has died in a hospice',
    longForm: [
      pt(`When someone dies in a UK hospice, the practicalities are well-supported by the hospice staff. Many hospices have small mortuary facilities or close arrangements with local funeral directors, so the immediate care of your loved one is handled gently.`),
      h2('Hospice staff handle the immediate practicalities'),
      pt(`The hospice doctor will verify the death and issue the Medical Certificate of Cause of Death. Hospice nursing staff will support the family with whatever they need — including giving you private time with your loved one. Hospices are specifically designed for these moments and handle them with great care.`),
      h2('Choosing a funeral director'),
      pt(`The hospice will not pressure you to use any specific funeral director. You have free choice. Many families ring around in the first day or two, comparing prices and approach. Best Direct Cremation costs £1,499 all-inclusive (£250 optional Priority Care for collection from a hospice without on-site mortuary facilities, taking the maximum to £1,749).`),
      h2('Hospices with their own mortuaries'),
      pt(`Some larger hospices (typically Marie Curie or Sue Ryder hospices) have small on-site mortuaries where your loved one can be cared for for 1-3 days before the funeral director collects them. In this case, no Priority Care fee is needed — collection is from a proper mortuary during normal working hours.`),
      h2('Smaller hospices and community settings'),
      pt(`Smaller hospices and home-hospice arrangements typically don't have mortuary facilities. In this case, the funeral director collects your loved one within a few hours of death (Priority Care collection, £250 fee).`),
      h2('What to expect next'),
      pt(`Once your loved one is in the local funeral director's care, you register the death at the local register office within 5 days. The funeral director handles all the cremation paperwork. The cremation takes place 1-2 weeks later. The ashes are returned within 5-14 days.`),
      h2('Anticipatory grief and hospice families'),
      pt(`Many families who have spent time with a hospice often experience anticipatory grief — they have been grieving through the months of illness. Direct cremation, by separating the practicalities (the cremation) from the personal (the memorial), gives these families the time and space to organise something genuinely meaningful when they're ready, rather than rushing into a formal funeral while still processing the loss.`),
      ...ctaSection('cremation-when-someone-dies-in-hospice'),
    ],
    faqs: standardFaqs,
  },
  // ====== "AFTER" / MEMORIAL family ======
  {
    slug: 'memorial-after-direct-cremation',
    title: 'Memorial After Direct Cremation — How to Plan One',
    modifier: 'memorial-after',
    serviceNoun: 'direct cremation',
    intentMatch: 'Post-cremation — planning a memorial later',
    longForm: [
      pt(`A memorial after a direct cremation is one of the great strengths of choosing direct cremation. It separates the practicalities (the cremation itself) from the personal (the gathering), letting families create something genuinely meaningful in their own time, in a venue that matters.`),
      h2('When to hold the memorial'),
      pt(`There's no rule. Some families hold a memorial within 1-2 weeks of the cremation, while emotions are fresh and family are still gathered. Others wait until a meaningful date — the deceased's birthday, the anniversary of their death, their wedding anniversary. Some wait until summer because they want to gather outdoors. Right time = whenever your family is ready and logistics work.`),
      h2('Where to hold it'),
      pt(`The most powerful memorials are in venues that matter. A favourite pub, a beach, a community hall the deceased volunteered at, a cricket club they played for, a family garden. Indoor venues work in winter; outdoor venues in summer. Avoid generic hired halls when something more meaningful is available.`),
      h2('Who to invite'),
      pt(`Anyone the deceased would have wanted there. You're not constrained by what fits in a 25-minute crematorium service. You can invite 200 people if the venue holds them. The invitation should make clear: this is a memorial (not a religious service), what time, what to wear ("wear what you like" or "wear something colourful"), and whether to RSVP.`),
      h2('What happens during it'),
      pt(`The structure is up to you. Typical pattern: welcome (often from a celebrant or family member), tributes from family and friends, open mic, music, food and drink, photo display, slideshow. Some families include a moment of scattering ashes; others save that for a separate intimate occasion. There are no rules.`),
      h2('Music and atmosphere'),
      pt(`The deceased's favourite music, played freely. Photos around the venue. A playlist of meaningful songs running through dinner. Drinks and food they enjoyed. The aim is recreating the feeling of being with them — celebrating the life they lived.`),
      h2('Cost'),
      pt(`Memorials cost what you make them. A pub function room can be free if you spend on food and drink. A community hall might cost £100-£300. Catering ranges from sandwiches and tea (a few hundred pounds for 50 people) to a sit-down meal (£25-£50 per head). Many families ask attendees to bring a dish, which spreads the cost.`),
      ...ctaSection('memorial-after-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'what-happens-to-ashes-after-cremation',
    title: 'What Happens to Ashes After a Cremation?',
    modifier: 'after',
    serviceNoun: 'cremation',
    intentMatch: 'Informational — process question',
    longForm: [
      pt(`After a cremation, the ashes (also called cremains) are returned to the family by the funeral director — typically in a simple urn or scatter tube. What happens next is entirely up to you, with no time pressure. Many families take weeks or months to decide.`),
      h2('Timeline'),
      pt(`The cremation itself takes 1-2 hours. The ashes are then cooled and processed. Within 5-14 days of the cremation, the ashes are returned to the funeral director and made available for collection or delivery to the family.`),
      h2('What ashes are, physically'),
      pt(`Cremation ashes are bone fragments that have been processed into a fine, pale grey powder. An average adult produces about 3-4 kg of ashes (around 6-9 lbs). They are clean, dry, and safe to handle.`),
      h2('Scattering ashes'),
      pt(`The most common choice. You can scatter ashes almost anywhere with the landowner's permission. Private land: get permission. Public parks or beaches: most local authorities allow scattering — check first. Rivers and at sea: the Environment Agency advises 1km from intakes and bridges. Many crematoria have Gardens of Remembrance where ashes can be scattered for a fee (£100-£300).`),
      h2('Keeping ashes at home'),
      pt(`No legal restriction on keeping ashes at home indefinitely. Many families do — either temporarily while they decide or permanently. Decorative urns range from £20 for a simple wooden box to £200+ for hand-thrown ceramic pieces.`),
      h2('Interring ashes'),
      pt(`Ashes can be interred (buried) in an existing family grave, in a cremation memorial garden, or in a dedicated ashes plot. Typical cost: £200-£800 for the interment plus any memorial stone.`),
      h2('Memorial jewellery and keepsakes'),
      pt(`A growing option: a small amount of ashes incorporated into a pendant or piece of jewellery, turned into a small glass keepsake, pressed into a vinyl record or piece of artwork. Cost: £50-£500+. Several UK companies specialise in this.`),
      h2('Splitting ashes between family members'),
      pt(`Many families divide ashes so each branch of the family has a portion. Legal and easy to arrange — the funeral director or crematorium can supply multiple small urns.`),
      ...ctaSection('what-happens-to-ashes-after-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== Process / time-of-death family ======
  {
    slug: 'how-to-arrange-a-direct-cremation',
    title: 'How to Arrange a Direct Cremation — Step by Step',
    modifier: 'how-to',
    serviceNoun: 'direct cremation',
    intentMatch: 'Process-driven',
    longForm: [
      pt(`Arranging a direct cremation in the UK is a simple, well-defined process. From the first call to the return of ashes typically takes 2-3 weeks. This guide walks through every step.`),
      h2('Step 1 — Call us'),
      pt(`Call Best Direct Cremation on 0333 242 1405 — a real person answers, 24 hours a day. We take basic details: who has died, where they are now, your relationship to them, and a contact number. No commitment, no high-pressure sales.`),
      h2('Step 2 — Confirm and we dispatch'),
      pt(`Once you confirm you want to proceed, we send a local funeral director to collect your loved one. Hospital collection: during normal working hours, included in the £1,499 base price. Home, care home, hospice collection: Priority Care, typically within 4-12 hours, £250 optional add-on (maximum total £1,749).`),
      h2('Step 3 — Register the death'),
      pt(`You register the death at the local register office within 5 days (8 in Scotland). You'll need the Medical Certificate of Cause of Death from the doctor. The registrar issues the Death Certificate and the Green Form that goes to the funeral director.`),
      h2('Step 4 — Care and paperwork'),
      pt(`Your loved one is cared for in the local funeral director's mortuary. The funeral director obtains all the necessary cremation paperwork — including the doctor's cremation certificates (Form Cremation 4 and 5, or Form Cremation 6 from the coroner if applicable).`),
      h2('Step 5 — The cremation'),
      pt(`On the appointed day, the funeral director takes your loved one to a local crematorium in a simple coffin. The cremation is dignified, private, and follows the same standards as any other cremation. There is no service.`),
      h2('Step 6 — Ashes returned'),
      pt(`Within 5-14 days of the cremation, the ashes are returned to you in a simple urn or scatter tube. You can collect them from the local funeral director or have them posted to you.`),
      h2('Step 7 — Memorial (optional)'),
      pt(`Many families hold a personal memorial later — at home, in a pub, at a community hall, outdoors. There's no time pressure and no rules. The memorial is separate from the cremation and can be planned with the freedom direct cremation gives you.`),
      ...ctaSection('how-to-arrange-a-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== More targeted long-tail ======
  {
    slug: 'direct-cremation-cost-uk',
    title: 'Direct Cremation Cost UK 2026 — What You Should Pay',
    modifier: 'cost',
    serviceNoun: 'direct cremation',
    intentMatch: 'Cost-focused, price comparison',
    longForm: [
      pt(`Direct cremation cost in the UK in 2026 ranges from £1,400 to £2,200 depending on the provider. Best Direct Cremation costs £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection fee for non-hospital collections — maximum total £1,749.`),
      h2('What the price should include'),
      pt(`Every credible all-in direct cremation price should cover: collection of the deceased; professional care in a local mortuary; a simple coffin suitable for cremation; all legal paperwork (doctor's certificates, Green Form); the cremation at a local crematorium; the return of ashes. If a quote excludes any of these at the headline price, it's not really an all-in figure.`),
      h2('Price by major UK provider'),
      pt(`Pure Cremation: ~£1,950. Co-op Funeralcare: ~£1,995. Dignity: ~£2,200. Aura: ~£1,400-£1,700. Simplicity: ~£1,200-£1,500. Cremation Direct: ~£1,300-£1,500. Best Direct Cremation: £1,499 all-inclusive.`),
      h2('The cheapest credible price'),
      pt(`Below £1,400, you're typically looking at a centralised operation where your loved one may be transported significant distances. Or hidden fees that emerge at the point of need (most commonly the Priority Care charge for non-hospital collections, which can add £400-£500).`),
      h2('What drives the price'),
      pt(`Local funeral director's overhead (premises, staff, mortuary, vehicles): £600-£900. The crematorium fee: £500-£900 depending on location. The coffin: £100-£250. Statutory paperwork including doctor's certificates: £160-£200. Funeral director's margin: 10-20% on top.`),
      h2('Why we charge £1,499'),
      pt(`£1,499 reflects the true cost of delivering a proper direct cremation through a local independent funeral director, plus a fair margin to keep them in business. There's no centralised hub overhead and no surprise fees. The £250 Priority Care add-on covers the additional work involved in collecting someone outside a hospital mortuary.`),
      h2('Hidden costs to watch for'),
      pt(`The most common hidden costs: Priority Care fees (£250-£500); out-of-hours collection fees; mileage charges over a certain distance; doctor's certificate fees not included in the headline price; "premium" coffin upgrades pushed at the point of need. Always confirm the all-in price including all of these before signing up.`),
      h2('Help if you can\'t afford it'),
      pt(`The Funeral Expenses Payment from the DWP can cover £1,000+ towards costs for people on certain benefits. The Children's Funeral Fund covers most fees if a child under 18 has died. As a last resort, a Public Health Funeral arranged by the local council provides a basic service at no cost.`),
      ...ctaSection('direct-cremation-cost-uk'),
    ],
    faqs: standardFaqs,
  },
  // ====== "WHY" / DECISION family ======
  {
    slug: 'why-choose-direct-cremation',
    title: 'Why Choose Direct Cremation? 9 Reasons Families Pick It',
    modifier: 'why',
    serviceNoun: 'direct cremation',
    intentMatch: 'Decision-stage — gathering reasons',
    longForm: [
      pt(`Direct cremation is the fastest-growing UK funeral type, now accounting for around one in every five UK funerals. Here are the nine most common reasons families choose it.`),
      h2('1. Cost'),
      pt(`Direct cremation costs £1,400-£1,700 — around two-thirds less than the £4,510 average UK funeral. The cost saving versus a traditional cremation is typically £3,000. Money saved can go to a personal memorial, the wake, or simply remain in the family.`),
      h2('2. Simplicity'),
      pt(`Direct cremation removes the formal ceremony at the crematorium. No celebrant, no music to choose, no order of service to print, no chapel slot to book. The practicalities are handled simply and quickly.`),
      h2('3. Less stress on the family'),
      pt(`Arranging a traditional funeral within days of a death is genuinely hard work — and at the worst possible time. Direct cremation reduces what the family has to do to a minimum: register the death, sign the cremation authority, wait for ashes to be returned.`),
      h2('4. Freedom to memorialise later'),
      pt(`Direct cremation separates the practicalities from the personal. The cremation happens promptly. The memorial can happen whenever the family is ready — weeks, months, even a year later — in a venue and at a time that genuinely matters.`),
      h2('5. The deceased asked for it'),
      pt(`Many people specifically ask for the simplest possible funeral in their will or in conversations with family. Direct cremation matches this wish. Following it honours their preferences.`),
      h2('6. Less anxiety for the dying'),
      pt(`For people facing a terminal diagnosis, knowing their funeral is taken care of and won't burden the family is a genuine source of peace. Direct cremation makes this easier to arrange and pay for.`),
      h2('7. No formal religious requirement'),
      pt(`For families who are not actively religious — now more than half the UK population — a formal religious service at the crematorium feels increasingly out of step. Direct cremation removes the religious requirement entirely while leaving space for the family to do something personal later.`),
      h2('8. Environmental considerations'),
      pt(`A direct cremation has a meaningfully lower environmental footprint than a traditional funeral. No floral tributes (significant CO2 from transport and refrigeration), no embalming chemicals, no hearse procession. Still some CO2 from the cremation itself, but the rest of the funeral's footprint is removed.`),
      h2('9. Aligned with modern preferences'),
      pt(`Direct cremation is becoming the modern UK default — chosen by people who prefer modern, low-key approaches over traditional, formal ceremonies. As cultural preferences shift, direct cremation increasingly feels like the obvious choice for many families.`),
      ...ctaSection('why-choose-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== Service-noun synonyms ======
  {
    slug: 'cremation-only-service',
    title: 'Cremation Only Service UK — What It Means',
    modifier: 'only',
    serviceNoun: 'cremation only',
    intentMatch: 'Researching cremation only meaning',
    longForm: [
      pt(`A "cremation only" service is another term for direct cremation: a cremation without a formal funeral service at the crematorium. The term emphasises what the service includes (just the cremation) and excludes (no ceremony, no attendance, no celebrant).`),
      h2('What "cremation only" includes'),
      pt(`Collection of the deceased; professional care in a mortuary; a simple coffin; the legal paperwork; the cremation itself; the return of ashes. Nothing else is included by default — no celebrant, no music, no chapel slot, no flowers, no procession, no embalming.`),
      h2('Cost'),
      pt(`Cremation only services typically cost £1,400-£1,700 in the UK in 2026. Best Direct Cremation costs £1,499 all-inclusive (£250 optional Priority Care for non-hospital collections, maximum total £1,749).`),
      h2('When is this the right choice?'),
      pt(`Cremation only suits families who want the practicalities handled quickly and cheaply, with the personal element handled separately (or not at all). It's increasingly chosen by families who plan to hold a memorial later, by people who don't want a formal religious service, and by anyone who prefers simplicity.`),
      h2('What you can add on'),
      pt(`Some providers (including Best Direct Cremation through partner funeral directors) allow you to add specific elements at the time of need: a viewing before the cremation, a brief moment at the funeral director's premises, an upgraded coffin, an alternative urn. These are typically priced individually.`),
      ...ctaSection('cremation-only-service'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'cremation-without-service',
    title: 'Cremation Without Service — What You Get',
    modifier: 'without-service',
    serviceNoun: 'cremation',
    intentMatch: 'Wants cremation but no formal service',
    longForm: [
      pt(`A cremation without service — also called direct cremation, unattended cremation, or cremation only — is a cremation that happens without a formal ceremony at the crematorium. No family present, no celebrant, no music, no readings, no committal.`),
      h2('Why this is increasingly popular'),
      pt(`Around one in every five UK funerals now skips the formal crematorium service. Families choose this for cost (£1,400-£1,700 vs £4,510 for a traditional funeral), simplicity, the freedom to organise a personal memorial later, or because the deceased specifically asked for "no fuss".`),
      h2('What still happens with care and dignity'),
      pt(`Even without a service, the cremation itself is dignified. Your loved one is collected by a professional funeral director, cared for in a proper mortuary, transported to the crematorium in a proper funeral vehicle, and cremated to the same standards as any other cremation. The dignity is in the care, not in the ceremony.`),
      h2('Best Direct Cremation\'s approach'),
      pt(`We deliver every cremation locally through a vetted independent funeral director — one we have personally checked for facilities, NAFD or SAIF accreditation, staff training and standards of care. £1,499 all-inclusive, with £250 optional Priority Care for non-hospital collections.`),
      h2('Memorial separately'),
      pt(`Most families who choose cremation without service hold a personal memorial later — at home, in a meaningful venue, with the people who mattered to the deceased. This separation of cremation (practical) and memorial (personal) is increasingly seen as the most considered way to organise a modern UK funeral.`),
      ...ctaSection('cremation-without-service'),
    ],
    faqs: standardFaqs,
  },
  // ====== Specific keyword targets ======
  {
    slug: 'direct-cremation-1499',
    title: 'Direct Cremation £1,499 — Best Direct Cremation Pricing',
    modifier: 'price-point',
    serviceNoun: 'direct cremation',
    intentMatch: 'Specific price match',
    longForm: [
      pt(`Direct cremation at £1,499 is Best Direct Cremation's all-inclusive price for a dignified direct cremation delivered locally by a vetted independent funeral director. The £1,499 is the price you pay — no hidden extras at the point of need.`),
      h2('What you get for £1,499'),
      pt(`Collection from a hospital or coroner's mortuary. Professional care of your loved one in a local independent funeral director's mortuary. A simple coffin suitable for cremation. All legal paperwork including doctor's certificates and the registrar's Green Form. The cremation at a local crematorium. The return of ashes (or scattering at the crematorium garden of remembrance).`),
      h2('When the price is £1,749'),
      pt(`If the person who has died is not at a hospital or coroner's mortuary, a Priority Care collection is needed. This is an optional £250 add-on to cover the additional work — out-of-hours response, immediate dispatch, dignified collection from a home or care home or hospice. Maximum total £1,749.`),
      h2('Why £1,499 is the right price'),
      pt(`£1,499 covers the actual cost of delivering a proper direct cremation through a local independent funeral director — their staff, premises, vehicles, mortuary, paperwork, and the crematorium fee — plus a fair margin. There is no centralised hub overhead and no surprise fees added at the point of need.`),
      h2('Comparison with other UK providers'),
      pt(`Pure Cremation: ~£1,950 (centralised). Co-op Funeralcare: ~£1,995 (own branch network). Dignity: ~£2,200 (own crematoria network). Best Direct Cremation: £1,499 (local independent FD network). Best Direct Cremation is the lowest UK direct cremation price for genuinely local delivery.`),
      ...ctaSection('direct-cremation-1499'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: '24-hour-funeral-directors',
    title: '24 Hour Funeral Directors UK — Real Person, Any Hour',
    modifier: '24-hour',
    serviceNoun: 'funeral directors',
    intentMatch: 'Urgent — out-of-hours need',
    longForm: [
      pt(`Death doesn't keep office hours. Best Direct Cremation answers 0333 242 1405 24 hours a day, every day — a real person, every call. Whether someone has just died at 2am, 6pm on a Sunday, or anywhere in between, you can reach a human being who can dispatch a local funeral director immediately.`),
      h2('Why 24-hour matters'),
      pt(`When someone dies at home, in a care home or in a hospice (rather than in a hospital with mortuary facilities), the funeral director needs to collect them within a few hours. If the death happens overnight or at the weekend, this is when a 24-hour answering service genuinely matters. Many UK funeral directors only answer business hours and rely on automated answering services for out-of-hours calls — leaving families waiting until Monday morning.`),
      h2('How our 24-hour service works'),
      pt(`Call 0333 242 1405. A real Best Direct Cremation team member answers — a person, not a chatbot, not an answering service. We take essential details (who has died, where they are now, your contact number) and dispatch a vetted local funeral director within hours. The out-of-hours response is included in the price — no extra fee for evenings, weekends or bank holidays.`),
      h2('Costs'),
      pt(`Best Direct Cremation costs £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection fee for non-hospital collections. There is no additional fee for out-of-hours response — Priority Care covers any collection from outside a hospital regardless of time of day.`),
      h2('When you really need 24-hour'),
      pt(`Most families won't actually need to arrange the funeral at 2am — but they often need to talk to someone who knows what's happening and can reassure them. Many calls in the middle of the night are families simply needing the next-step guidance: who to call, what to do, what comes next. A real person on the other end of the phone makes a huge difference at that moment.`),
      ...ctaSection('24-hour-funeral-directors'),
    ],
    faqs: standardFaqs,
  },
  {
    slug: 'no-frills-funeral',
    title: 'No Frills Funeral UK — Direct Cremation Explained',
    modifier: 'no-frills',
    serviceNoun: 'funeral',
    intentMatch: 'No-frills minded',
    longForm: [
      pt(`A "no frills funeral" in the UK is almost always a direct cremation — the cremation is carried out simply and dignified, with everything ceremonial removed. No flowers, no celebrant, no music, no procession, no chapel service. Just the essentials, done properly.`),
      h2('What "no frills" actually means'),
      pt(`Practically, a no-frills funeral = a direct cremation. The cremation itself happens. Your loved one is treated with full dignity and professional care. But everything else that families traditionally arrange — the limousines, the floral tributes, the order of service, the chapel booking, the celebrant — is removed.`),
      h2('What you pay for'),
      pt(`The collection of your loved one. Professional care in a mortuary. A simple coffin. The legal paperwork. The cremation itself. The return of ashes. That's it. Best Direct Cremation provides all of this for £1,499 (or £1,749 with Priority Care).`),
      h2('Why people choose no-frills'),
      pt(`Cost is a big factor. A traditional UK funeral costs £4,510 on average; a direct cremation costs around £1,499. The saving is around £3,000. But no-frills funerals are also chosen for non-financial reasons: simplicity, the deceased's stated preference, the freedom to memorialise later, or just a modern preference for low-key approaches.`),
      h2('Dignity isn\'t a frill'),
      pt(`The critical thing about no-frills funerals is that the no-frills part should only apply to the ceremony — not the care your loved one receives. Best Direct Cremation removes the formal ceremony but keeps the dignified professional care that any family deserves. Every cremation is delivered by a vetted local independent funeral director with their own mortuary, vehicles and trained staff.`),
      ...ctaSection('no-frills-funeral'),
    ],
    faqs: standardFaqs,
  },
  // ====== Modern + religious framing ======
  {
    slug: 'non-religious-cremation',
    title: 'Non-Religious Cremation UK — Direct or Humanist',
    modifier: 'non-religious',
    serviceNoun: 'cremation',
    intentMatch: 'Non-religious families researching options',
    longForm: [
      pt(`More than half of UK adults now identify as non-religious. Non-religious cremation has become the norm rather than the exception, and families have two main paths: a fully non-religious attended cremation with a civil or humanist celebrant, or a direct cremation followed by a personal memorial.`),
      h2('Option 1 — Non-religious attended cremation'),
      pt(`A civil celebrant or humanist celebrant leads a 20-30 minute service at the crematorium. Family and friends attend. The service is tailored entirely to the deceased — their character, key stories, favourite music, what mattered to them. No prayers, no hymns, no religious content (unless specifically requested at the family's preference). Cost: £2,500-£3,800.`),
      h2('Option 2 — Direct cremation + personal memorial'),
      pt(`No service at the crematorium — the cremation itself is unattended. Families hold a personal memorial separately, often weeks later, in a venue and at a time that means something. Direct cremation costs £1,400-£1,700 (Best Direct Cremation £1,499); the memorial costs whatever you make it.`),
      h2('Which is right for which family?'),
      pt(`Attended cremation works if you want a brief moment of formal gathering at the crematorium and don't want to wait to organise something later. Direct cremation + personal memorial works if you want to organise the perfect gathering on your own terms, in a venue and at a time that genuinely matters, rather than being confined to a 25-minute crematorium service.`),
      h2('Finding a celebrant'),
      pt(`Civil Ceremonies and Humanists UK both register accredited celebrants. Your funeral director will recommend several local options. The celebrant typically spends 1-2 hours with the family beforehand to understand the deceased — the resulting service is genuinely personal.`),
      h2('Best Direct Cremation\'s role'),
      pt(`We offer direct cremation only — we don't currently offer attended cremation. If direct cremation is right for your family, we provide it at £1,499 all-inclusive, delivered locally by a vetted independent funeral director. If you want an attended cremation with a humanist or civil celebrant, you'll need a traditional funeral director (look for NAFD or SAIF accreditation).`),
      ...ctaSection('non-religious-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== Specific provider alternative ======
  {
    slug: 'alternative-to-pure-cremation',
    title: 'Alternative to Pure Cremation — Best Direct Cremation',
    modifier: 'alternative',
    serviceNoun: 'pure cremation',
    intentMatch: 'Searching for Pure Cremation alternatives',
    longForm: [
      pt(`Pure Cremation is the UK's largest dedicated direct cremation operator, with its main mortuary in Andover, Hampshire and a network of owned crematoria. If you're looking for an alternative — typically because you want a more local, more personal service — Best Direct Cremation offers a genuine local alternative at a lower price.`),
      h2('The key difference: local vs centralised'),
      pt(`Pure Cremation operates a centralised model. Their drivers collect your loved one and may transport them a significant distance to their Andover mortuary. Cremation then takes place at one of their owned crematoria. Best Direct Cremation operates a local model. Your loved one is collected by a vetted local independent funeral director, cared for in their local mortuary, and cremated at a local crematorium — typically all within 10-25 miles of your home.`),
      h2('Price comparison'),
      pt(`Pure Cremation: ~£1,950 for direct cremation. Best Direct Cremation: £1,499 all-inclusive (£250 optional Priority Care for non-hospital collections, maximum £1,749).`),
      h2('Service quality'),
      pt(`Both are professional, dignified, FCA-aware operators. The differences are structural rather than quality-based: Pure Cremation's scale means well-tested processes; Best Direct Cremation's local model means more personal continuity.`),
      h2('Who Pure Cremation suits'),
      pt(`Families who prioritise the largest dedicated operator with the longest track record. Families who don't mind transportation distance and prefer a single national point of contact. Families who want the security of a heavily-marketed brand.`),
      h2('Who Best Direct Cremation suits'),
      pt(`Families who want their loved one cared for close to home. Families who want the cremation to take place locally, often at a crematorium that means something to them. Families who want a local funeral director's personal touch and accountability. Families who want the lowest credible price for proper local delivery.`),
      h2('Reviews and reputation'),
      pt(`Both providers have strong customer reviews on Trustpilot and Google. Read recent reviews specifically — both companies evolve their service over time.`),
      ...ctaSection('alternative-to-pure-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== Outcome focused ======
  {
    slug: 'dignified-cremation',
    title: 'Dignified Cremation UK — What Dignity Looks Like in 2026',
    modifier: 'dignified',
    serviceNoun: 'cremation',
    intentMatch: 'Wants reassurance about dignity',
    longForm: [
      pt(`Dignified cremation is what every family deserves — and what every UK funeral provider should deliver, regardless of price. Dignity is in the care your loved one receives, not in the elaborate ceremony around it. This guide explains what dignified cremation looks like and how to ensure your loved one is treated with the care they deserve.`),
      h2('What dignity actually means'),
      pt(`Dignity in cremation means: your loved one is treated as a person from the moment of collection to the return of ashes; they are handled by trained professionals who treat their work with the seriousness it deserves; they are cared for in proper mortuary facilities, not stored or warehoused; the cremation is carried out one person at a time with proper identification; the ashes are returned with care.`),
      h2('What dignity is not'),
      pt(`Dignity is not the cost of the coffin. Dignity is not the celebrant fee. Dignity is not the number of limousines. Dignity is not the size of the floral tributes. These are ceremonial elements that some families find meaningful — but they have nothing to do with the dignity of how your loved one is cared for.`),
      h2('How dignity can fail'),
      pt(`Dignity fails when: providers centralise to the point that your loved one is transported significant distances and cared for in unfamiliar facilities; when staff are stretched too thin to give every family proper attention; when the cremation is rushed or batched; when the ashes are mixed or mislabelled. None of this should ever happen — but it has happened in the UK funeral industry and the consumer must be alert to it.`),
      h2('How Best Direct Cremation guarantees dignity'),
      pt(`Every cremation is delivered by a vetted local independent funeral director — one we have personally checked for facilities, NAFD or SAIF accreditation, staff training, and standards of care. Your loved one stays close to home throughout. The local funeral director is a real person with a reputation in your community who takes personal pride in their work.`),
      h2('What to ask any cremation provider'),
      pt(`Where will my loved one be collected from and how far will they be transported? Where will they be cared for between collection and cremation? Which crematorium will be used? Who will physically handle my loved one? Are you NAFD or SAIF accredited? Honest providers answer all five directly. Evasive providers tell you something is wrong.`),
      ...ctaSection('dignified-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== Money-back / guarantee ======
  {
    slug: 'all-inclusive-direct-cremation',
    title: 'All-Inclusive Direct Cremation UK — No Hidden Fees',
    modifier: 'all-inclusive',
    serviceNoun: 'direct cremation',
    intentMatch: 'Looking for transparent pricing',
    longForm: [
      pt(`An "all-inclusive" direct cremation should mean one price covering everything you need — with no surprise extras at the point of need. Best Direct Cremation costs £1,499 all-inclusive. The only optional cost is the £250 Priority Care collection fee for non-hospital collections — fully disclosed before you commit. Maximum total £1,749.`),
      h2('What our all-inclusive price covers'),
      pt(`Collection from a hospital or coroner's mortuary (Priority Care add-on for collection from home, care home or hospice). Professional care of your loved one in a local independent funeral director's mortuary. A simple coffin suitable for cremation. All legal paperwork including the Medical Cremation Certificates and the Green Form. The cremation at a local crematorium. The return of ashes to you or scattering at the crematorium garden of remembrance.`),
      h2('What "all-inclusive" doesn\'t cover'),
      pt(`A service at the crematorium. A celebrant or minister. Hearses or limousines. Music or readings. Flowers. An upgraded coffin. Embalming. Memorial arrangements. Formal notices. Alternative urns. These are not part of direct cremation and most families don't want them — but they would all add to the cost if you did.`),
      h2('Beware of false "all-inclusive" claims'),
      pt(`Some providers advertise a low all-inclusive price (£950-£1,200) but then add £400-£500 for Priority Care when they realise the person who died is at home rather than in hospital. This is a common pricing tactic — the headline isn't really all-inclusive. Always ask for the all-in price including Priority Care before signing up.`),
      h2('How we guarantee no hidden fees'),
      pt(`Best Direct Cremation publishes the Standardised Price List (required by the Competition and Markets Authority) in our footer — confirming our pricing in the format every UK funeral director must use. The price we quote is the price you pay. No upselling at the point of need.`),
      ...ctaSection('all-inclusive-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
  // ====== Religious specific ======
  {
    slug: 'christian-direct-cremation',
    title: 'Christian Direct Cremation — A Compatible Choice?',
    modifier: 'christian',
    serviceNoun: 'direct cremation',
    intentMatch: 'Christian families considering direct cremation',
    longForm: [
      pt(`Direct cremation is increasingly chosen by Christian families across the UK, including by practising Anglicans, Catholics, Methodists and others. The decision is personal and depends on your specific Christian tradition and your family's preferences. This guide explains how direct cremation fits with Christian practice.`),
      h2('Cremation in Christianity'),
      pt(`Most Christian denominations now accept cremation. The Church of England accepted cremation in 1944. The Roman Catholic Church accepted cremation in 1963 (with conditions on the treatment of ashes). Most Protestant denominations have always accepted cremation. Eastern Orthodox traditions remain primarily burial-focused.`),
      h2('Direct cremation specifically'),
      pt(`Direct cremation is the practical aspect (the cremation itself, with no formal service at the crematorium). Most Christian families who choose direct cremation also hold a separate Christian memorial service afterwards — at home, at the family church, or somewhere meaningful. The local minister can lead a memorial service even without the body present.`),
      h2('When direct cremation works for Christian families'),
      pt(`When the family wants a Christian funeral but cost is a concern (direct cremation costs £1,499 vs £4,510 average traditional). When the family wants the personal memorial to be at the local church (where the deceased was a parishioner) rather than at the crematorium. When the family lives spread across the country and wants flexibility to gather later. When the deceased specifically asked for "no fuss".`),
      h2('When direct cremation may not work'),
      pt(`When the family specifically wants a traditional Christian funeral led by the parish minister at the crematorium. When Catholic tradition requires the body present at the funeral mass. When the family lives close together and the formal funeral is the focal point of gathering.`),
      h2('How to combine direct cremation with a Christian memorial'),
      pt(`Arrange direct cremation through Best Direct Cremation (£1,499 all-inclusive). The cremation happens within 1-2 weeks. Then plan a Christian memorial service at the local church — most parish ministers will lead a memorial service for anyone in the parish, regardless of attendance frequency. The memorial can be a full Eucharist, a memorial service of remembrance, or simply a brief gathering. The ashes can be present (in an urn) or interred in the churchyard.`),
      ...ctaSection('christian-direct-cremation'),
    ],
    faqs: standardFaqs,
  },
];

// ============================================================
// HIGH-PRIORITY GAP PAGES
// ============================================================
// Additional generic-term pages built to WINNING-PAGE-FORMAT-SPEC.md
// covering high-volume UK search queries where competitors currently rank
// but we don't. Full ~1,500-2,200 word cornerstones each.
GENERICS.push(...GAP_PAGES);
GENERICS.push(...GAP_PAGES_BATCH_2);

// ============================================================
// INGEST
// ============================================================
async function run() {
  console.log(`Ingesting ${GENERICS.length} generic-term landers into ${PROJECT_ID}/${DATASET}…`);
  let count = 0;

  for (const g of GENERICS) {
    const doc = {
      _type: 'genericTerm',
      _id: `generic-${g.slug.replace(/\//g, '-')}`,
      title: g.title,
      slug: { _type: 'slug', current: g.slug },
      modifier: g.modifier,
      serviceNoun: g.serviceNoun,
      // intentMatch (schema field): opening hero paragraph derived from intent
      intentMatch: [pt(g.intentMatch + ' — direct cremation from £1,499 all-inclusive, delivered locally by a vetted independent funeral director. Call 0333 242 1405, 24 hours a day.')],
      longForm: enrichBlocks(g.longForm, g.slug),
      faqs: g.faqs.map(f => ({
        _type: 'faq',
        _key: f.q.slice(0, 12).replace(/\s/g, ''),
        question: f.q,
        answer: [pt(f.a)],
      })),
      showPriceLadder: true,
      showComparisonStrip: true,
      seo: {
        metaTitle: g.title,
        metaDescription: g.intentMatch + ' — £1,499 all-inclusive, delivered locally. Call 0333 242 1405.',
      },
    };
    await client.createOrReplace(doc);
    count++;
    console.log(`  ✓ /services/${g.slug}/`);
  }

  console.log(`\nDone. ${count} generic-term landers created.`);
}

run().catch(err => { console.error(err); process.exit(1); });
