/**
 * Ingest 24 Help & Guidance articles into Sanity.
 *
 * 12 extended existing topics + 12 new topics. Each article ~1,500 words.
 *
 * Usage:  npx tsx scripts/ingest-help.ts
 */
import { createClient } from '@sanity/client';
import { Linkifier } from './lib/linkify';

/**
 * Auto-enrich a built body array with in-prose internal links.
 * Run inside the per-article save loop with a fresh Linkifier each time.
 */
function enrichBody(bodyBlocks: any[], slug: string): any[] {
  const linkifier = new Linkifier({ currentSlug: slug });
  return bodyBlocks.map(block => {
    if (block?.style === 'normal' && block?.children?.[0]?.text && (!block.markDefs || block.markDefs.length === 0)) {
      return linkifier.pt(block.children[0].text);
    }
    return block;
  });
}

const PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || '80kiihr6';
const DATASET    = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
const TOKEN      = process.env.SANITY_API_WRITE_TOKEN;
if (!TOKEN) throw new Error('Set SANITY_API_WRITE_TOKEN before running ingestion.');
const client = createClient({ projectId: PROJECT_ID, dataset: DATASET, apiVersion: '2024-10-01', useCdn: false, token: TOKEN });

const pt = (text: string) => ({ _type: 'block', style: 'normal', children: [{ _type: 'span', text }], markDefs: [] });
const h2 = (text: string) => ({ _type: 'block', style: 'h2', children: [{ _type: 'span', text }], markDefs: [] });

const CTA = pt(`If you need help arranging a direct cremation, Best Direct Cremation is available 24 hours a day on 0333 242 1405. A real person — never a chatbot — every call. £1,499 all-inclusive, delivered locally by a vetted independent funeral director.`);

type Article = { slug: string; title: string; intent: string; excerpt: string; bodyBlocks: any[]; faqs?: Array<{q: string; a: string}> };

const HELP: Article[] = [
  // -------- 12 extended existing topics --------
  {
    slug: 'what-to-do-when-someone-dies',
    title: 'What to Do When Someone Dies — A Step-by-Step UK Guide',
    intent: 'process',
    excerpt: 'A clear, calm, plain-English guide to the practical steps after someone has died — from the first hour to the funeral and beyond.',
    bodyBlocks: [
      pt(`When someone close to you dies, the world seems to stop. For most people, this is the first time they have had to deal with the practicalities of a death — and there is a lot to do at a moment when you may feel least able to do it. This guide walks you through exactly what happens, step by step.`),
      h2('First few hours — was the death expected or unexpected?'),
      pt(`What you need to do first depends on where and how the person died. If the death was expected at home (someone with a terminal illness under hospice or GP care), call the GP surgery or community nursing team — they will arrange for a doctor to attend and verify the death. There is no rush. You do not need to call 999.`),
      pt(`If the death was unexpected, or you are not sure, call 999. Paramedics will attend, verify the death, and if there is anything to investigate, they will involve the police and the coroner. Do not move the person or touch anything in the room.`),
      pt(`If the person died in hospital or a hospice, the staff will take care of the immediate practicalities. The deceased will be moved to the hospital mortuary, and you will be given paperwork — usually a "Medical Certificate of Cause of Death" — that you take to the local register office to register the death.`),
      h2('Registering the death'),
      pt(`Most deaths must be registered within 5 days in England, Wales and Northern Ireland (8 days in Scotland). You register at the register office for the area where the person died — not where they lived. Book an appointment online via your local council's website.`),
      pt(`You'll need: the Medical Certificate of Cause of Death (issued by the doctor or hospital), the person's full name and any previous names, date and place of birth, last address, occupation, NHS number if known, and details of any state pension or benefits they received.`),
      pt(`The registrar will issue: a Death Certificate (you'll usually want several certified copies — £11 each — for banks, pensions and probate); a "Green Form" (Certificate for Burial or Cremation) which goes to the funeral director; and a notification slip for state benefits.`),
      h2('Tell us once'),
      pt(`At the register office, ask about "Tell Us Once" — a free government service that notifies most public bodies (HMRC, DWP, Passport Office, DVLA, the council) in one go. It saves enormous amounts of admin. The registrar will give you a unique reference number to use within 28 days.`),
      h2('Choosing a funeral director'),
      pt(`You can take your time to choose. There is no need to commit to the first funeral director you call. Look for: NAFD or SAIF membership, transparent pricing displayed on their website (the CMA requires this), reviews on Google or Trustpilot, and a local, real-person presence rather than just a website.`),
      pt(`A direct cremation typically costs £1,400-£1,700 all-inclusive in 2026. An attended cremation typically costs £2,500-£3,800. A traditional funeral typically costs £4,500+. Get prices in writing before you commit.`),
      h2('What the funeral director does'),
      pt(`Once you've appointed a funeral director, they will: collect the person from the place of death (24/7 if needed), care for them in their mortuary, handle all the paperwork including the cremation forms, book the crematorium or cemetery, arrange the service (if any), provide transport, and return the ashes if cremation.`),
      h2('Beyond the funeral'),
      pt(`After the funeral comes the longer admin: probate (legal authority to deal with the estate), notifying any private pensions and insurance, closing bank accounts, dealing with property, and any inheritance tax. This can take 6-12 months to fully complete.`),
      pt(`Citizens Advice has a comprehensive bereavement section. The "What to do after a death" service on GOV.UK walks you through every legal step. Most banks have dedicated bereavement teams who will guide you through closing accounts.`),
      CTA,
    ],
    faqs: [
      { q: 'How long do I have to register a death?', a: '5 days in England, Wales and Northern Ireland; 8 days in Scotland. Book an appointment at the register office for the area where the person died.' },
      { q: 'Do I have to use the funeral director the hospital suggests?', a: 'No. Hospitals must let you take time to choose. You are free to use any funeral director you wish.' },
      { q: 'What is the cheapest type of funeral?', a: 'A direct cremation is the lowest-cost UK funeral, typically £1,400-£1,700 all-inclusive in 2026.' },
    ],
  },
  {
    slug: 'what-is-direct-cremation',
    title: 'What Is a Direct Cremation? A Complete Guide',
    intent: 'informational',
    excerpt: 'Everything you need to know about direct cremation in the UK — what it includes, what it does not, how it differs from a traditional funeral, and why one in five UK funerals is now direct.',
    bodyBlocks: [
      pt(`A direct cremation is a simple, dignified cremation without a service at the crematorium. The deceased is collected, cared for, and cremated — and the ashes are returned to the family. There is no formal ceremony at the crematorium, no procession, no hymns. Families are free to hold their own memorial or celebration of life separately, on their own terms.`),
      pt(`Direct cremation has grown rapidly in the UK and now accounts for around one in every five funerals (Co-op Funeralcare Media Centre, 2024). The growth reflects a deeper shift in how families think about funerals — many no longer want or need the formality of a traditional crematorium service.`),
      h2('What is included'),
      pt(`A typical UK direct cremation includes: collection of the deceased (often 24/7), professional care in a local mortuary, a simple coffin suitable for cremation, all legal paperwork, the cremation itself at a local crematorium, and the return of ashes — usually in a simple urn or scatter tube, delivered to the family or available for collection.`),
      h2('What is not included'),
      pt(`Direct cremation does not include: a service or ceremony at the crematorium, attendance by family or friends at the cremation itself, a hearse or limousine for family transport, a celebrant or minister, music or readings, flowers, an upgraded coffin, a viewing of the deceased, embalming, or any wake or reception. Some of these can be added at extra cost from many providers; others are simply not part of the direct cremation model.`),
      h2('How direct cremation differs from traditional funerals'),
      pt(`A traditional funeral typically costs £4,510 in 2026 (SunLife Cost of Dying Report 2026). A direct cremation typically costs £1,400-£1,700 in 2026 — around two-thirds less. The difference reflects what is left out: no hearse procession, no chapel service, no celebrant, no large-scale flowers. What remains is the essential, dignified care of the deceased and the cremation itself.`),
      h2('Why people choose direct cremation'),
      pt(`Cost is one reason, but rarely the only one. Many families say they prefer the freedom of arranging their own memorial later — somewhere meaningful — without being tied to a 25-minute crematorium service that doesn't feel personal. Others want to spare their family the cost and stress. Some have specifically requested direct cremation in their will. And many simply prefer simplicity.`),
      h2('Who is direct cremation right for?'),
      pt(`Direct cremation suits people who want simplicity, families who plan to hold their own memorial separately, those who want to keep costs low without compromising on dignity, and anyone who simply does not want a formal crematorium service. It is not the right choice for those who want a service at the crematorium itself, who want family present at the cremation, or who have strong religious traditions requiring a specific funeral form.`),
      h2('Choosing a direct cremation provider'),
      pt(`Look for: clear, all-inclusive pricing on the website, a local funeral director delivering the service (not a centralised hub), NAFD or SAIF accreditation, transparent terms on what is and is not included, and 24-hour real-person phone access. Avoid: providers that won't quote a single all-in price, anyone who centralises the cremation hundreds of miles from home, and any provider who can't tell you which crematorium will be used.`),
      h2('The Best Direct Cremation approach'),
      pt(`Best Direct Cremation delivers every cremation locally through a network of vetted independent funeral directors. Your loved one stays close to home — collected, cared for, and cremated by a local professional with their own mortuary, vehicles and premises. £1,499 all-inclusive, with the only optional cost being a £250 Priority Care collection if needed (maximum total £1,749). Available 24 hours a day on 0333 242 1405.`),
      CTA,
    ],
    faqs: [
      { q: 'Is direct cremation the same as a pauper\'s funeral?', a: 'No. A direct cremation is a chosen funeral, paid for, with the deceased treated with full dignity and care. A "public health funeral" (the modern term for a pauper\'s funeral) is what happens when no one can pay — local authorities arrange a basic cremation funded by the council.' },
      { q: 'Can I attend a direct cremation?', a: 'Not at the crematorium itself — the cremation is unattended. However, you can ask the funeral director about a brief moment with your loved one before they leave for the crematorium.' },
      { q: 'What happens to the ashes?', a: 'They are returned to the family in a simple urn or scatter tube. You can collect them or have them delivered.' },
    ],
  },
  {
    slug: 'cost-of-a-funeral',
    title: 'How Much Does a Funeral Cost in the UK in 2026?',
    intent: 'cost',
    excerpt: 'A complete breakdown of UK funeral costs in 2026, with average prices by type, what makes up the cost, and how to keep funeral costs down.',
    bodyBlocks: [
      pt(`The average UK funeral cost in 2026 is £4,510 (SunLife Cost of Dying Report 2026), a 4.7% rise on 2025. That figure averages all funeral types together — actual costs range from £1,400 for a direct cremation to over £10,000 for a traditional burial in some parts of the UK.`),
      h2('By funeral type'),
      pt(`Direct cremation: £1,400-£1,700 in 2026. Attended cremation (simple plan with family present): £2,500-£3,800. Traditional cremation (full ceremonial with hearse, limousines, celebrant): £4,500-£5,500. Traditional burial: £5,000-£10,000+ depending on plot cost. The plot itself in London can cost £20,000+.`),
      h2('What makes up the cost'),
      pt(`Funeral director fees (collection, care, coffin, paperwork, vehicles): £1,500-£3,500 depending on plan. Disbursements (third-party fees the funeral director pays on your behalf — cremation fee, doctor's certificate, celebrant): £600-£1,200. Add-ons (additional limousines, flowers, music, alternative urns, memorial extras): £200-£2,000+.`),
      h2('Why funeral costs have risen'),
      pt(`Funeral costs in the UK have risen by 5% per year on average over the last decade — significantly above general inflation. The main drivers: rising crematorium and burial fees (local authorities have increased these sharply), higher fuel and vehicle costs, premises and staff cost inflation, and rising fees from third parties like doctors and celebrants.`),
      h2('How to keep funeral costs down'),
      pt(`The single biggest decision is direct cremation versus an attended or traditional funeral. Switching from a traditional funeral (£4,510 average) to a direct cremation (£1,499 at Best Direct Cremation) saves around £3,000 — about two-thirds. Beyond that, smaller savings come from: choosing a simpler coffin, holding the wake at home or a community venue rather than a pub, asking for flowers from one source rather than full floral tributes, and choosing a weekday morning service rather than a peak Friday afternoon slot.`),
      h2('Help if you can\'t afford a funeral'),
      pt(`If you genuinely cannot afford a funeral, three options exist. The Funeral Expenses Payment from the DWP can cover £1,000+ towards costs for people on low income or benefits. Charities including Down to Earth (in London) and Quaker Social Action's Fair Funerals can help. As a last resort, a Public Health Funeral (also called a council funeral) is arranged by the local authority — basic but dignified.`),
      h2('Are funeral costs rising faster than wages?'),
      pt(`Yes. UK average earnings have grown by around 3% per year over the last decade. Funeral costs have grown by 5% per year. This means funerals have become progressively less affordable as a share of household income — which is part of why direct cremation has grown so quickly.`),
      h2('Where to get clear pricing'),
      pt(`Every UK funeral director must by law (the CMA's Funerals Market Investigation Order 2021) publish a Standardised Price List on their website and display one in their branch. If a funeral director won't quote a single all-in price or won't show you their Standardised Price List, walk away. Best Direct Cremation's Standardised Price List is linked in our footer.`),
      CTA,
    ],
    faqs: [
      { q: 'What is the cheapest funeral in the UK?', a: 'A direct cremation, typically £1,400-£1,700 in 2026. Best Direct Cremation costs £1,499 all-inclusive.' },
      { q: 'Why do funeral costs vary so much by region?', a: 'Crematorium and burial fees, set by local authorities, vary substantially. London, the south-east, and major cities tend to be most expensive. Rural areas tend to be cheaper.' },
      { q: 'Are funeral plans cheaper than paying at the time?', a: 'They lock in today\'s price against future inflation, but the headline cost is typically similar to paying now. The advantage is inflation protection over the long term.' },
    ],
  },
  {
    slug: 'how-direct-cremation-works',
    title: 'How Direct Cremation Works — Step by Step',
    intent: 'process',
    excerpt: 'A clear walk-through of the direct cremation process from first call to ashes returned.',
    bodyBlocks: [
      pt(`Direct cremation is simpler than a traditional funeral, but every step still needs to happen with care and dignity. Here is exactly what happens from the moment you first call us.`),
      h2('Step 1 — Your first call'),
      pt(`When someone dies, you call us on 0333 242 1405. A real person answers — 24 hours a day. We take some basic details: who has died, where they are now, who you are and your relationship, and the best contact number to reach you. No commitment, no high-pressure sales. If you want to think about it overnight, we wait.`),
      h2('Step 2 — Collection'),
      pt(`Once you confirm you want to proceed, we send a local funeral director to collect your loved one. If they are in a hospital or hospice, we coordinate with them directly. If they are at home, in a care home, or anywhere outside a hospital, our Priority Care service handles collection — typically within 4-12 hours of your call.`),
      pt(`The collection is dignified and professional. Two trained staff in dark, plain vehicles. No branded vans, no flashing lights. Your loved one is moved into the funeral director's own mortuary nearby.`),
      h2('Step 3 — Care in the mortuary'),
      pt(`Your loved one stays in the local funeral director's mortuary while the paperwork is completed. They are treated with dignity throughout — refrigerated, identified, and prepared for cremation. We do not embalm in a direct cremation as it is unnecessary for an unattended cremation.`),
      h2('Step 4 — Registering the death and paperwork'),
      pt(`While we care for your loved one, you register the death at the local register office. Most appointments are available within 1-2 working days. The registrar issues the Death Certificate (you may want several certified copies) and the "Green Form" (cremation certificate). The funeral director also obtains the necessary cremation forms from the doctor or coroner.`),
      h2('Step 5 — The cremation'),
      pt(`On the appointed day, the funeral director takes your loved one to a local crematorium in a simple coffin. There is no service, no procession, no music. The cremation is dignified, private, and exactly the same standard as any other cremation — just without the ceremonial elements that family would attend.`),
      h2('Step 6 — Ashes returned'),
      pt(`The ashes are returned to you within 7-14 days. You can collect them from the local funeral director's premises, or we can post them to you. Many families like to scatter them somewhere meaningful, hold a memorial later, or keep them at home.`),
      h2('Step 7 — Beyond the cremation'),
      pt(`Direct cremation gives you the freedom to remember your loved one your way. Some families hold a memorial service weeks or months later. Others scatter ashes at a favourite place. Some simply mark the moment quietly with close family. There is no right or wrong way.`),
      CTA,
    ],
  },
  {
    slug: 'cost-of-direct-cremation',
    title: 'Cost of Direct Cremation in the UK 2026',
    intent: 'cost',
    excerpt: 'How much does direct cremation cost in 2026? Detailed UK pricing, what is included, and how to compare providers.',
    bodyBlocks: [
      pt(`Direct cremation in the UK in 2026 costs between £1,400 and £1,700 for the most reputable providers. Best Direct Cremation is £1,499 all-inclusive, with a £250 Priority Care fee if needed for a non-hospital collection — maximum total £1,749. That makes direct cremation around two-thirds cheaper than the £4,510 average UK funeral.`),
      h2('What you should pay'),
      pt(`A high-quality, ethical direct cremation in 2026 costs £1,400-£1,700 with a local provider. Anything cheaper (sub-£1,200) usually means corners are being cut — centralised collection from miles away, lowest-spec coffin, no Priority Care, or hidden fees. Anything significantly more expensive (£1,800+) is usually a centralised national operator charging a brand premium over their actual cost.`),
      h2('What is included at Best Direct Cremation'),
      pt(`£1,499 includes: collection of your loved one, professional care in a local mortuary, a simple coffin suitable for cremation, all paperwork, the cremation itself at a local crematorium, and the return of ashes. Priority Care (collection from home, care home, hospice or anywhere outside a hospital) is an optional £250 add-on — maximum total £1,749.`),
      h2('What is not included'),
      pt(`The price does not include: a service or ceremony, an upgraded coffin, embalming, hearse or limousine, alternative urns, headstones or memorials, or a wake. These are not part of a direct cremation and most families do not want them.`),
      h2('How to compare providers'),
      pt(`Ask every provider four questions: (1) What is your single all-in price including everything except optional add-ons? (2) Where will my loved one be collected from and how far will they be transported? (3) Which crematorium will be used? (4) Are you NAFD or SAIF accredited? Honest providers answer all four directly. Evasive providers tell you what to watch out for.`),
      h2('Why some providers are cheaper'),
      pt(`The very cheapest direct cremation providers (£900-£1,200) achieve their price by centralising operations — collection drivers from regional hubs, a single mortuary serving large areas, and cremations at a small number of owned crematoria. This means your loved one may be transported 100+ miles for the cremation. For some families that is acceptable; for many, it is not.`),
      h2('Why we charge what we charge'),
      pt(`£1,499 covers a local independent funeral director's actual cost to deliver a dignified service — their staff, premises, vehicles, mortuary, paperwork and the crematorium fee — plus a fair margin. There is no centralised hub. Your loved one stays close to home. That is what makes a Best Direct Cremation different from a centralised low-cost operator.`),
      CTA,
    ],
  },
  {
    slug: 'cremation-vs-burial',
    title: 'Cremation vs Burial — Costs, Trends and How to Choose',
    intent: 'comparison',
    excerpt: 'A comparison of cremation and burial in the UK — costs, environmental impact, religious considerations, and how to decide.',
    bodyBlocks: [
      pt(`Around 78% of UK funerals in 2025 were cremations (Cremation Society of Great Britain statistics). Burial remains important for religious, cultural and personal reasons — but it is increasingly expensive and increasingly the minority choice. This guide compares the two and explains how to decide.`),
      h2('Cost'),
      pt(`Cremation is significantly cheaper. A direct cremation costs £1,400-£1,700 in 2026. A traditional cremation with a service costs £4,500+. A traditional burial costs £5,000-£10,000+, before adding the cost of the plot itself (which can range from £1,500 in rural areas to £20,000+ in central London). The plot is the biggest variable — and the biggest reason burial costs have risen so sharply.`),
      h2('Religious and cultural considerations'),
      pt(`Some religious traditions strongly prefer burial — particularly Islam, Judaism and Orthodox Christianity. Most modern Catholic and Anglican families now accept cremation, though preferences vary. Hindu, Sikh and Buddhist traditions favour cremation. If religious tradition matters to you or your family, this may settle the decision.`),
      h2('Environmental impact'),
      pt(`Both have environmental costs. A cremation produces approximately 245 kg of CO2 (Resomation Ltd, industry data) and uses significant natural gas. A burial requires land that cannot be returned to other use, and a conventional coffin and embalming chemicals add to the impact. Greener alternatives — woodland or natural burial without embalming, or new water-cremation technologies (alkaline hydrolysis) — are growing but limited in availability.`),
      h2('Where the deceased "is"'),
      pt(`Burial creates a fixed place — a grave you can visit. Many families find this comforting. Cremation produces ashes that can be kept at home, scattered somewhere meaningful, or interred in a memorial garden. There is no fixed location unless the family chooses one. For some this is liberating; for others it is a loss.`),
      h2('Practicalities'),
      pt(`Burial requires more lead time — the grave has to be prepared, the cemetery has to be available. Cremation can typically be arranged within 1-2 weeks. Cremation also has fewer practical constraints around the body's condition. Burial requires the family to maintain the grave; cremation does not, unless ashes are interred.`),
      h2('How to decide'),
      pt(`Ask: what is the religious or cultural expectation in our family? What did the deceased want (and is there anything in writing or said clearly)? What can we afford? What kind of memorial or place of remembrance matters to us? Answer those four and the decision usually becomes clear.`),
      CTA,
    ],
  },
  {
    slug: 'choosing-a-funeral-director',
    title: 'How to Choose a Funeral Director — A Practical Checklist',
    intent: 'process',
    excerpt: 'A step-by-step checklist for choosing a funeral director — what to ask, what to verify, and what red flags to watch for.',
    bodyBlocks: [
      pt(`Choosing a funeral director is one of the most important decisions you'll make when arranging a funeral. The CMA's investigation found significant variation in pricing and quality across the UK funeral industry — and most families have no benchmark for what good looks like. This checklist explains exactly what to look for.`),
      h2('Look for accreditation'),
      pt(`Two main accreditation bodies: the National Association of Funeral Directors (NAFD) and the Society of Allied and Independent Funeral Directors (SAIF). Both require members to follow professional standards, have complaints processes, and undergo periodic inspections. A funeral director that belongs to neither has chosen not to be held to those standards — that's a red flag.`),
      h2('Look for transparent pricing'),
      pt(`Every UK funeral director must by law publish a Standardised Price List on their website (CMA Funerals Market Investigation Order 2021). If you can't find it, ask. If they won't show you one, walk away. Look for: a single headline all-in price, clear what's included and what's not, separate disbursements clearly stated, and no surprise extras.`),
      h2('Look for local presence'),
      pt(`A genuine local funeral director has: their own premises (not just an address), their own mortuary, their own vehicles, and staff who live and work locally. Many "local" funeral directors are now branches of national chains using a local-sounding name. There's nothing wrong with that, but you should know which is which.`),
      h2('Read reviews carefully'),
      pt(`Google Reviews, Funeral Guide, and Trustpilot all have funeral director reviews. Read several recent ones. Watch for patterns: complaints about pricing surprises, about staff behaviour at the moment of collection, about how the deceased was cared for. One bad review is noise; a pattern is signal.`),
      h2('Questions to ask'),
      pt(`(1) Are you NAFD or SAIF accredited? (2) Can I see your Standardised Price List? (3) Where will my loved one be cared for — at your premises or elsewhere? (4) Which crematorium will be used? (5) What is included in your price and what costs extra? (6) What is your out-of-hours contact procedure? (7) Can I see the coffin before I commit? Honest answers to all seven are the baseline.`),
      h2('Red flags'),
      pt(`High-pressure sales tactics ("decide now or the price goes up"); refusal to quote a single all-in price; vagueness about where the deceased will be cared for; centralisation of operations across large areas; no clear premises to visit; no NAFD or SAIF accreditation; consistently bad reviews.`),
      h2('Best Direct Cremation\'s network'),
      pt(`Every funeral director in the Best Direct Cremation network must be NAFD or SAIF accredited, have their own premises and mortuary, be locally established, and meet our quality standards for staff training and dignity in care. We verify every one — so you don't have to.`),
      CTA,
    ],
  },
  {
    slug: 'arranging-a-cremation',
    title: 'Arranging a Cremation in the UK — The Complete Process',
    intent: 'process',
    excerpt: 'Step-by-step guide to arranging a cremation in the UK — paperwork, timing, costs, and choices.',
    bodyBlocks: [
      pt(`Arranging a cremation in the UK involves more paperwork than burial because the law requires extra checks before any cremation can take place. This guide explains exactly what needs to happen, in what order, and how long each step takes.`),
      h2('Medical certificates'),
      pt(`Before a cremation can go ahead, two medical certificates are required (in most cases). Form Cremation 4 is completed by the doctor who attended the deceased during their last illness. Form Cremation 5 is completed by an independent doctor who has examined the body separately. These two forms are then checked by the crematorium's medical referee before cremation is approved.`),
      pt(`If the death was reported to the coroner (because it was sudden, unexpected or unexplained), the coroner issues Form Cremation 6 instead — and the two doctor forms are not needed. This is more common than people expect; around 40% of UK deaths are reported to the coroner.`),
      h2('Registering the death'),
      pt(`Register at the local register office — within 5 days in England, Wales and Northern Ireland (8 days in Scotland). You'll receive a Death Certificate (get several copies, £11 each) and a Certificate for Cremation ("Green Form") that goes to the funeral director.`),
      h2('Choosing a crematorium'),
      pt(`Most families use the crematorium closest to where the deceased lived. The funeral director will recommend a crematorium and arrange the booking. Crematorium fees vary widely — £750-£1,200 depending on location and time slot.`),
      h2('The coffin'),
      pt(`The coffin must be suitable for cremation — typically a simple wooden coffin without metal handles or fittings that would not burn. For direct cremation, a basic coffin is included in the all-in price. For attended cremation, you can choose between basic, mid-range and premium coffins (cardboard, willow, traditional veneer, solid wood) at varying cost.`),
      h2('The cremation itself'),
      pt(`The cremation takes 1-2 hours. The coffin is identified and carefully placed in the cremator. Heat reduces the body to bone fragments, which are then processed to ashes. The ashes are placed in a labelled container (urn or scatter tube) and returned to the funeral director — and then to the family — typically within 5-7 days.`),
      h2('Attended vs unattended'),
      pt(`An attended cremation includes a service in the crematorium chapel — typically 20-30 minutes, with a celebrant, music, readings and a brief committal. Family members are present. An unattended cremation (direct cremation) has no service at the crematorium; the family is not present. Both involve exactly the same dignified cremation process — the difference is the ceremony around it.`),
      h2('Timing'),
      pt(`In the UK, most cremations take place 1-2 weeks after death. The main constraints are the medical paperwork (1-3 working days) and the crematorium's available slots. Direct cremation can sometimes be faster because there is no need to coordinate a service date with family.`),
      CTA,
    ],
  },
  {
    slug: 'ashes-what-to-do',
    title: 'What to Do With Ashes — UK Guide',
    intent: 'process',
    excerpt: 'Options for what to do with ashes after cremation — scattering, keeping, interring, jewellery and more.',
    bodyBlocks: [
      pt(`After a cremation, the ashes are returned to the family — typically in a simple urn or scatter tube. What happens next is entirely up to you, and there is no time pressure. Many families take weeks or months to decide. This guide explains the main options.`),
      h2('Scattering ashes'),
      pt(`Scattering is the most common choice. You can scatter ashes almost anywhere with the landowner's permission. On private land — yours or someone else's — get permission. In public parks or open spaces, most local authorities allow scattering but check first. In rivers and at sea, the Environment Agency advises 1km from intakes and bridges and ideally near the source of the river.`),
      pt(`Many crematoria have a Garden of Remembrance where ashes can be scattered or interred for a fee (typically £100-£300). Some families like the formality of this; others prefer somewhere more personal.`),
      h2('Keeping ashes at home'),
      pt(`There is no legal restriction on keeping ashes at home indefinitely. Many families do — either temporarily while they decide what to do, or permanently. Decorative urns range from a few pounds for a simple wooden box to several hundred pounds for a hand-thrown ceramic piece.`),
      h2('Interring ashes in a grave'),
      pt(`Ashes can be interred (buried) in an existing family grave, in a cremation memorial garden, or in a dedicated ashes plot. Costs vary by cemetery, typically £200-£800 for the interment plus any memorial stone.`),
      h2('Memorial jewellery and keepsakes'),
      pt(`A growing option: a small amount of ashes is incorporated into a piece of jewellery (often a pendant), turned into a small glass keepsake, or pressed into a vinyl record or piece of artwork. Costs range from £50-£500+. Several UK companies specialise in this.`),
      h2('Splitting ashes between family members'),
      pt(`Many families divide ashes so each branch of the family has a portion. This is entirely legal. The funeral director or crematorium can supply multiple small urns. Many families combine: some kept at home, some scattered at a meaningful place, some kept by a particular relative.`),
      h2('How long can ashes wait?'),
      pt(`Indefinitely. There is no deadline. Many families take weeks or months to decide. Some keep ashes for years before scattering. There is no right answer and no wrong answer.`),
      CTA,
    ],
  },
  {
    slug: 'celebrant-vs-minister',
    title: 'Celebrant vs Minister — Which Should You Choose?',
    intent: 'process',
    excerpt: 'The difference between funeral celebrants and ministers in the UK, and how to choose for an attended cremation or traditional funeral.',
    bodyBlocks: [
      pt(`If you're arranging an attended cremation or traditional funeral, you'll need someone to lead the service. There are two main options: a celebrant or a minister (priest or religious leader). They differ in style, cost and approach.`),
      h2('What a minister provides'),
      pt(`A minister leads a religious service in their faith tradition. For a Church of England funeral, this would typically be a vicar or curate. For a Catholic funeral, a priest. Other denominations and faiths have equivalents. The service follows the established liturgy of that faith — prayers, readings, hymns, blessings. There is comfort in tradition and ritual.`),
      pt(`Cost: ministers don't typically "charge" but a contribution to the church is expected — usually £200-£400. Sometimes higher in larger churches or for more elaborate services.`),
      h2('What a celebrant provides'),
      pt(`A celebrant leads a non-religious or partly religious service tailored entirely to the deceased. They typically spend an hour or two with the family beforehand to understand the person — their life, character, stories, what music they loved. The resulting service is personal and unique.`),
      pt(`Cost: civil celebrants typically charge £200-£350. Specialist humanist celebrants (registered with Humanists UK) typically charge £250-£450.`),
      h2('How to choose'),
      pt(`If religious tradition matters to the family or the deceased — choose a minister. If the deceased was not religious, or you want a personal service tailored to who they were — choose a celebrant. A hybrid is possible: a celebrant who includes a hymn or prayer at the family's request.`),
      h2('Finding a celebrant'),
      pt(`Your funeral director will normally recommend several. Look for: experience (ask how many funerals they've led), references or reviews, and someone who feels right when you meet them. The Civil Ceremonies website and Humanists UK both have searchable directories.`),
      h2('Finding a minister'),
      pt(`Through the local church the deceased attended. If they were not a regular churchgoer, the parish minister can usually still lead the service — most parish ministers will lead a funeral for anyone in their parish regardless of attendance.`),
      h2('Direct cremation alternative'),
      pt(`If you don't want a service at the crematorium at all, a direct cremation removes the need for any minister or celebrant. Many families then hold a separate memorial later — and you can use a celebrant or minister at that memorial, in a venue that means something to your family.`),
      CTA,
    ],
  },
  {
    slug: 'funeral-without-religion',
    title: 'How to Plan a Non-Religious Funeral',
    intent: 'process',
    excerpt: 'A practical guide to planning a non-religious or humanist funeral in the UK — what to include, who can lead it, and how to make it personal.',
    bodyBlocks: [
      pt(`More than half of the UK population now identifies as non-religious (British Social Attitudes Survey 2023). Non-religious funerals — civil ceremonies and humanist funerals — have become the norm rather than the exception. This guide explains what they involve and how to plan one.`),
      h2('Civil ceremony vs humanist funeral'),
      pt(`Civil ceremonies are non-religious but can include some religious elements at the family's request (a hymn, a moment of reflection, a brief blessing). Humanist funerals are entirely non-religious and follow a clear philosophical framework — life is finite, love and memory are what endures, the focus is on the person's life rather than the afterlife.`),
      h2('Who leads it'),
      pt(`Civil celebrants and humanist celebrants both lead funerals. Civil Ceremonies UK and Humanists UK both register celebrants. Your funeral director will recommend several local options. A funeral director who tries to push only one celebrant should be questioned — you have free choice.`),
      h2('What is typically included'),
      pt(`Welcome and introduction. Tribute (the celebrant tells the story of the person's life — informed by family conversations). Music — often pieces the deceased loved or that meant something to the family. Readings — poetry, prose, family contributions. Reflection — a moment of silence, often with music playing. Committal — the formal end of the service. Closing words.`),
      h2('How to make it personal'),
      pt(`The single biggest factor: spend time with the celebrant beforehand. A good celebrant spends 1-2 hours with the family understanding the deceased's character, key stories, favourite music, key relationships, achievements and quirks. The resulting tribute genuinely captures who they were.`),
      h2('Music choices'),
      pt(`Most crematoria have a digital music system. You can play almost any music — pop, classical, jazz, folk, anything. Many families choose a meaningful piece for the entrance, a reflective piece for the middle, and a more uplifting piece for the exit. Three pieces is typical; some families have more.`),
      h2('Readings'),
      pt(`Family members reading something they wrote, a famous poem (W.H. Auden's "Funeral Blues" remains hugely popular), a quote from the deceased's favourite book, or a passage that captures their values. Readings can be 30 seconds or 5 minutes — there's no right length.`),
      h2('Direct cremation followed by a memorial'),
      pt(`Many non-religious families now choose direct cremation followed by a memorial later. This separates the practicalities (cremation) from the personal (memorial). The memorial can be held weeks or months later, in a venue that matters — a pub, a beach, a garden, a community hall — with the time and freedom to do it properly.`),
      CTA,
    ],
  },
  {
    slug: 'funeral-readings-and-poems',
    title: 'Funeral Readings and Poems — A Curated Selection',
    intent: 'reference',
    excerpt: 'Popular funeral readings and poems for UK funerals — religious and non-religious, classical and modern.',
    bodyBlocks: [
      pt(`Readings and poems are one of the most meaningful elements of a funeral or memorial. The right reading captures something true about the person who has died — and gives those present a moment to feel exactly what they need to feel.`),
      h2('Classic non-religious poems'),
      pt(`"Funeral Blues" by W.H. Auden — "Stop all the clocks, cut off the telephone…" The most-requested funeral poem in the UK. Devastating, perfect.`),
      pt(`"Do not stand at my grave and weep" by Mary Frye — "Do not stand at my grave and weep / I am not there, I do not sleep…" Comforting, gentle.`),
      pt(`"Remember" by Christina Rossetti — "Remember me when I am gone away…" A Victorian classic, still hugely powerful.`),
      pt(`"She Is Gone (He Is Gone)" by David Harkins — "You can shed tears that she is gone, or you can smile because she has lived…" Quoted at the Queen Mother's funeral. Hopeful, gentle.`),
      h2('Religious passages'),
      pt(`Psalm 23 — "The Lord is my shepherd…" — endures as the most-requested religious reading at UK funerals.`),
      pt(`Ecclesiastes 3:1-8 — "To everything there is a season…" — beautiful even for non-religious listeners.`),
      pt(`John 14:1-3 — "Let not your hearts be troubled…" — comforting for Christian families.`),
      h2('Modern and unexpected'),
      pt(`"The Dash" by Linda Ellis — about the dash between birth and death and what it represents. Increasingly popular.`),
      pt(`Henry Scott Holland — "Death is nothing at all…" — often misattributed but always moving.`),
      pt(`Quotes from the deceased's favourite book or song lyrics from a meaningful piece of music.`),
      h2('Family-written tributes'),
      pt(`Often the most moving readings are written by a family member. A few paragraphs about who the person was, a specific memory, what they meant. Doesn't have to be polished — heartfelt is more important than literary.`),
      h2('How to choose'),
      pt(`Ask: what would the deceased have liked? What captures who they were? What will the family find comforting? Three readings is typical for a 25-minute service — one classic, one personal, one reflective. The celebrant can help you choose.`),
      CTA,
    ],
  },

  // -------- 12 new topics --------
  {
    slug: 'bereavement-support',
    title: 'Bereavement Support — Where to Find Help',
    intent: 'support',
    excerpt: 'Where to find emotional support after a bereavement in the UK — charities, helplines, counselling and online resources.',
    bodyBlocks: [
      pt(`Losing someone you love is one of the hardest things any of us go through. Grief is not linear, doesn't have a deadline, and looks different for everyone. If you are struggling — even months or years after the loss — there is real, free help available.`),
      h2('Cruse Bereavement Support'),
      pt(`The UK's largest bereavement charity. Free helpline (0808 808 1677), online chat, regional support groups, and one-to-one counselling. Highly recommended as a first port of call for anyone struggling with grief.`),
      h2('The Good Grief Trust'),
      pt(`A coalition of UK bereavement charities. Their website helps you find the right support based on the type of loss — sudden, expected, child loss, sibling loss, partner, parent. Often the first signpost when you don't know what kind of support you need.`),
      h2('Marie Curie'),
      pt(`Particularly for families of people who died with a terminal illness or in palliative care. Free helpline (0800 090 2309), online community, and information about anticipatory grief.`),
      h2('Specialist support'),
      pt(`Child loss: Sands (stillbirth and neonatal), Child Bereavement UK. Partner loss: WAY (Widowed and Young, for those under 50), Widowed and Young UK. Sudden or violent death: Sudden, INQUEST. Bereaved children: Winston's Wish. Each has dedicated trained volunteers who have been through similar losses themselves.`),
      h2('GP and NHS'),
      pt(`Your GP can refer you for bereavement counselling on the NHS. Waiting lists vary, but in many areas counselling is available within 6-12 weeks. NHS Talking Therapies (formerly IAPT) accepts self-referrals in most areas. If grief is significantly impacting your daily life — sleep, eating, work, relationships — this is the right route.`),
      h2('Paid counselling'),
      pt(`If you can afford private counselling, the British Association for Counselling and Psychotherapy (BACP) has a searchable directory of accredited practitioners. Bereavement-specific counsellors typically charge £50-£90 per session.`),
      h2('What grief feels like'),
      pt(`There is no right way to grieve. Some people feel intense sadness immediately; others feel numb for weeks before it hits. Some people cry constantly; others can't cry at all. Some feel angry; others feel relieved (especially after a long illness). All of these are normal. Grief comes in waves — and even years on, certain dates or songs or smells can bring back the rawness of the early days.`),
      h2('When to seek help'),
      pt(`If grief is preventing you from functioning — sleeping, eating, working, looking after yourself or others — seek support sooner rather than later. If you have any thoughts of self-harm, call the Samaritans on 116 123 (free, 24/7) or your GP today.`),
      CTA,
    ],
  },
  {
    slug: 'probate-and-estate',
    title: 'Probate and Estate Administration — A Beginner\'s Guide',
    intent: 'legal',
    excerpt: 'What probate is, when it\'s needed, and how to administer an estate in the UK.',
    bodyBlocks: [
      pt(`Probate is the legal authority to deal with someone's estate (their property, money and possessions) after they die. It's a process that often confuses families because most people only encounter it once or twice in a lifetime. This guide explains what probate is, when it's needed, and how to do it.`),
      h2('When is probate needed?'),
      pt(`Probate is generally needed if the deceased: owned property (a house or flat) in their sole name, had bank accounts over £20,000-£50,000 (the threshold varies by bank), had investments or pensions that require probate to release, or owned anything significant that's only in their name.`),
      pt(`Probate is generally NOT needed if: all assets were jointly owned (automatically transferred to the survivor), the estate is very small (under £5,000 typically), or there's nothing to transfer.`),
      h2('Who applies for probate'),
      pt(`If there's a will, the named executor applies for a "Grant of Probate". If there's no will (the person died intestate), the next of kin applies for "Letters of Administration". Both give the same legal authority to deal with the estate.`),
      h2('The application process'),
      pt(`Apply online via GOV.UK or by post (form PA1P with a will, PA1A without). You'll need: the original will, the death certificate, an estimate of the estate's value, and the application fee (£300 for estates over £5,000 in 2026; free below that). Processing time is currently 4-16 weeks depending on workload.`),
      h2('Inheritance tax'),
      pt(`If the estate is worth more than £325,000 (the "nil-rate band"), inheritance tax may be due — 40% on the amount above the threshold. There are additional allowances for a main residence passed to direct descendants (up to £175,000) and for transfers between spouses (the unused allowance passes to the surviving spouse). Inheritance tax must be paid before probate is granted in most cases.`),
      h2('Doing it yourself vs hiring a solicitor'),
      pt(`Simple estates (one property, a few bank accounts, no inheritance tax) are doable yourself with patience. Complex estates (multiple properties, trusts, foreign assets, family disputes) benefit from a probate solicitor. Solicitor fees are typically 1-4% of the estate value, or hourly at £150-£300+.`),
      h2('Timing'),
      pt(`A simple probate takes 6-12 months from death to estate distribution. Complex estates can take 12-24 months. You can usually access enough funds for the funeral and immediate bills without full probate — most banks have a bereavement team that releases funds for funeral costs.`),
      h2('Where to get help'),
      pt(`Citizens Advice has free guidance. GOV.UK has the official process. The Society of Trust and Estate Practitioners (STEP) has a directory of qualified probate professionals. For specialised advice, hire a STEP-qualified solicitor.`),
      CTA,
    ],
  },
  {
    slug: 'writing-a-will',
    title: 'Writing a Will — Why, When and How',
    intent: 'planning',
    excerpt: 'A practical guide to writing a will in the UK — why everyone needs one, when to write it, and the cheapest reliable ways to do it.',
    bodyBlocks: [
      pt(`Only around 40% of UK adults have a valid will (Will Aid statistics). That means three in five families face the chaos of intestacy when someone dies — strangers' rules deciding where the estate goes, family disputes, delays, and often outcomes that the deceased would have hated. A will solves all of this.`),
      h2('Why everyone needs a will'),
      pt(`If you have any of these — a partner you're not married or in a civil partnership with (unmarried partners inherit nothing under intestacy rules), children from any relationship, specific wishes about who gets what, a business, property, or pets — you need a will. Without one, the law decides for you. It rarely matches what you would have wanted.`),
      h2('When to write or update'),
      pt(`Write your first will: when you buy property, when you have children, when you start cohabiting with a partner (unmarried partners get nothing under intestacy rules), or when you have anything of value. Update: when you marry (marriage usually invalidates a previous will), divorce, have more children, lose a parent, or significantly change your financial situation.`),
      h2('How to write a will'),
      pt(`Three main routes. (1) DIY using a will writing template (£10-£50, suitable only for very simple wills). (2) Will writing service (£50-£200 typical, useful for moderately simple wills — check the writer is accredited). (3) Solicitor (£150-£500 for a simple will, £500-£1,500+ for complex estates — the right choice if there's any complexity, blended families, or business interests).`),
      h2('Will Aid'),
      pt(`Every November, hundreds of UK solicitors take part in Will Aid — they write a basic will in exchange for a suggested donation (£100 single will, £180 mirror wills for a couple) which goes to nine major charities. It's a way to get a properly written will at low cost while supporting charity.`),
      h2('Key things to include'),
      pt(`(1) An executor — the person responsible for administering your estate. Often a family member; sometimes a solicitor. (2) Beneficiaries — who gets what. (3) Guardians for any children under 18. (4) Specific gifts (a piece of jewellery to a niece, a sum to a charity). (5) Funeral wishes — though these are not legally binding, they guide the family.`),
      h2('Storing your will'),
      pt(`Your will is only useful if it can be found. Store the original safely (a solicitor's office, a bank safety deposit box, or the National Will Register). Tell your executor where it is. A copy at home with key documents is fine; the original must be somewhere safe.`),
      h2('Reviewing your will'),
      pt(`Review every 5 years and after any major life event. Wills written years ago often don't reflect current life — different partners, more or fewer children, new houses, different finances.`),
      CTA,
    ],
  },
  {
    slug: 'organising-a-memorial',
    title: 'How to Organise a Memorial Service',
    intent: 'process',
    excerpt: 'A complete guide to planning a memorial service after a direct cremation or separately from the funeral.',
    bodyBlocks: [
      pt(`Many families now choose direct cremation followed by a separate memorial service — held weeks, months, or even a year after the death. This separates the practical (the cremation) from the personal (the gathering). This guide explains how to plan a memorial that genuinely honours the person.`),
      h2('When to hold it'),
      pt(`There is no rule. Some families hold a memorial within a couple of weeks. Others wait until the next significant anniversary — the deceased's birthday, the anniversary of their death, their wedding anniversary. Some wait until summer because they want to gather outdoors. The right time is whenever your family is ready and the practical logistics work.`),
      h2('Where to hold it'),
      pt(`The most powerful memorials are held somewhere meaningful — not just a hired hall. A favourite pub, a beach the deceased loved, a community hall where they volunteered, the cricket club they played for, the garden of a family home. Outdoor venues work in summer; community halls or pubs in winter.`),
      h2('Who to invite'),
      pt(`Anyone the deceased would have wanted there. You're not constrained by what fits in a crematorium chapel for 25 minutes — you can invite 200 people if the venue holds them. The invitation should make clear: this is a memorial (not a religious service), what time, what to wear (often "wear what you like" or "wear something colourful"), and whether to RSVP.`),
      h2('What happens during it'),
      pt(`The structure is up to you. A typical pattern: welcome (often from a celebrant or family member), a tribute or two (people who knew the deceased speak about them), open mic (anyone who wants to say something gets a chance), music, food and drink, photo display, perhaps a slideshow. Some families build in a moment of scattering ashes if they're doing that here.`),
      h2('Music and atmosphere'),
      pt(`Memorial services often have a different atmosphere from funerals — more celebration, less formality. The deceased's favourite music. Photos around the venue. A playlist of songs they loved running through dinner. Drinks and food they enjoyed. The aim is to recreate the feeling of being with them.`),
      h2('Cost'),
      pt(`Memorial services cost what you make them. A pub function room can be free if you spend on food and drink. A community hall might cost £100-£300. Catering ranges from sandwiches and tea (a few hundred pounds for 50 people) to a sit-down meal (£25-£50 per head). Many families ask attendees to bring a dish, which spreads the load.`),
      h2('Practicalities'),
      pt(`Send invitations 4-6 weeks ahead. Confirm the venue with deposit. Plan the music — make a playlist. Arrange photos to display. Brief anyone giving a tribute. On the day, have someone (not closest family) coordinate logistics so the family can be fully present.`),
      CTA,
    ],
  },
  {
    slug: 'living-with-a-terminal-diagnosis',
    title: 'Living With a Terminal Diagnosis — Practical and Emotional Steps',
    intent: 'support',
    excerpt: 'For families facing a terminal diagnosis — practical and emotional steps in the weeks and months ahead.',
    bodyBlocks: [
      pt(`A terminal diagnosis changes everything — for the person living with it, and for everyone close to them. The practical things to think about can feel overwhelming on top of the emotional weight. This guide breaks down both, gently.`),
      h2('Talking about it'),
      pt(`Most people instinctively want to protect their family by not talking about what's happening. But research from Marie Curie consistently shows the opposite — that open conversations with family about wishes, fears and practicalities reduce distress later and let the family feel they did right by the person they love. Start with one trusted person. Build from there.`),
      h2('Palliative care'),
      pt(`Palliative care is about quality of life, not just end of life. Marie Curie, Sue Ryder, Hospice UK and local hospices provide free palliative care — nursing visits, symptom management, emotional support, often around the clock in the final weeks. Many families don't realise this is available; ask the GP or specialist team for referral as early as possible.`),
      h2('Where to die'),
      pt(`Most people in the UK say they would prefer to die at home (Marie Curie Place of Death survey). In practice, around 30% do. The gap is closing but reflects barriers — care availability, family capacity, medical complexity. Talking openly with the medical team about what's possible matters. Hospices, hospitals and nursing homes are all reasonable options if home isn't possible.`),
      h2('Practical paperwork'),
      pt(`If a terminal diagnosis is confirmed, useful to organise: a will (or update an existing one), lasting power of attorney (so a trusted family member can manage finances and health decisions if the person becomes unable), Advance Decision (formerly known as a living will — your wishes about medical treatment), funeral wishes (where the person wants to be cremated or buried, who they want to lead the service, music, readings).`),
      h2('Funeral planning'),
      pt(`Many families find planning the funeral together — when the person is well enough to be part of the conversation — surprisingly meaningful. It removes uncertainty and gives the person a sense of control over how they will be remembered. Direct cremation is a popular choice in this situation because it removes the cost and complexity for the family, leaving room for a personal memorial later.`),
      h2('Emotional support'),
      pt(`Marie Curie, Macmillan, the British Association for Counselling and Psychotherapy, and your GP can all signpost to specialist counselling. Family support groups exist for many specific illnesses. Some hospices offer family support including for children and young people. Use them.`),
      h2('Anticipatory grief'),
      pt(`Grief doesn't start at death. Many family members grieve through the months of illness — for the person they're losing in real time. This is anticipatory grief and is normal. Allow it. Ask for support. Some bereavement charities (Cruse, Marie Curie) specifically support people experiencing anticipatory grief.`),
      CTA,
    ],
  },
  {
    slug: 'how-to-write-a-eulogy',
    title: 'How to Write a Eulogy',
    intent: 'process',
    excerpt: 'A practical guide to writing a eulogy or tribute for a funeral or memorial service — structure, examples, and what to avoid.',
    bodyBlocks: [
      pt(`Writing a eulogy is one of the hardest and most meaningful things you can do. It is a final act of attention to someone you loved — and done well, it leaves everyone in the room feeling they understood them a little better. This guide gives you a clear structure and practical tips.`),
      h2('What a eulogy is, and isn\'t'),
      pt(`A eulogy is a tribute that captures who the person was — their character, their relationships, their humour, their quirks. It is not a biography (don't list every job they ever had). It is not a sermon (avoid moralising). It is a portrait in words.`),
      h2('A simple structure'),
      pt(`(1) Opening — who you are and your relationship to them, one or two sentences. (2) Who they were — three or four qualities or themes that capture them. For each, a specific story or memory. (3) The harder bits — if relevant, briefly acknowledge difficulties or contradictions (most lives have them). (4) What they meant — to the family, to friends, to you. (5) Closing — a final image, a line they used to say, something that captures them.`),
      h2('Find specifics'),
      pt(`Generalities ("Dad was kind") are forgettable. Specifics ("Dad used to drive 40 miles to bring me a forgotten lunchbox without complaining once") land. For every quality you mention, find a specific memory that demonstrates it. The story does the work, not the adjective.`),
      h2('How long'),
      pt(`5-8 minutes is the sweet spot. Read aloud — it always sounds longer than you think. A 1,500-word eulogy is roughly 8 minutes. A 1,000-word eulogy is roughly 5 minutes. If in doubt, shorter is better. Better to leave people wishing for more than checking their watch.`),
      h2('Humour'),
      pt(`Good. A funeral that doesn't include any laughter has missed something. Laughter is part of love. The deceased's quirks, their funny stories, the awful jokes they used to tell — all of it belongs in a eulogy. Just make sure it's affectionate not cruel.`),
      h2('Practising'),
      pt(`Read it aloud to one person you trust. Time it. Mark places where you find it hard — that is normal, don't try to remove the emotion. Print it in 14pt with double spacing. Bring water. Don't apologise to the audience if you cry — the audience expects it and respects it.`),
      h2('If you can\'t do it on the day'),
      pt(`Many families ask the celebrant or a friend to read the eulogy on their behalf. There is no shame in this. The eulogy is what matters; who reads it is secondary. A pre-recorded video is also possible.`),
      h2('Examples to study'),
      pt(`Earl Spencer's eulogy at Diana, Princess of Wales' funeral. Brendan Cox's tribute to his wife Jo Cox. Eulogies on the Funeral Director's Almanac website. None of these are templates — they are examples of how specific, affectionate, honest writing creates a lasting tribute.`),
      CTA,
    ],
  },
  {
    slug: 'cremation-paperwork',
    title: 'Cremation Paperwork Explained',
    intent: 'process',
    excerpt: 'The legal paperwork required for a UK cremation — what each form does and who completes it.',
    bodyBlocks: [
      pt(`Cremation in the UK requires more paperwork than burial because the law requires extra checks before the cremation can take place. This guide explains every form and what each one does.`),
      h2('Form Cremation 4 — Medical Certificate'),
      pt(`Completed by the doctor who attended the deceased during their last illness. It confirms the cause of death and that the doctor has no reason to suspect anything that would prevent cremation. Cannot be completed if the doctor has not seen the deceased recently (within 14 days for hospital deaths, longer for community deaths).`),
      h2('Form Cremation 5 — Confirmatory Medical Certificate'),
      pt(`Completed by an independent second doctor — a Confirmatory Medical Examiner — who examines the body separately and confirms there is no reason to suspect anything suspicious. Required for most cremations except where the coroner is involved.`),
      pt(`The Cremation 4 + Cremation 5 system costs a small fee per doctor — typically £82 per certificate (£164 total). These costs are usually included in the funeral director's all-in price ("disbursements") and called "doctor's fees".`),
      h2('Form Cremation 6 — Coroner\'s Certificate'),
      pt(`Issued by the coroner instead of forms 4 and 5 if the death was reported to the coroner. This happens for: sudden or unexpected deaths, deaths from causes the doctor can't certify, deaths after a recent injury or operation, deaths in custody, deaths where there's any concern. Around 40% of UK deaths go through this route. There is no fee for Form Cremation 6.`),
      h2('Form Cremation 10 — Authority to Cremate'),
      pt(`Signed by the next of kin or whoever is arranging the funeral. Confirms they want the cremation to go ahead and confirms the details (name, date, crematorium). This is the legal authority for the cremation to take place.`),
      h2('Form Cremation 13 — Statement of Truth (changes since 2024)'),
      pt(`Following changes to the regulations in 2024, additional certifications have been introduced. Your funeral director will know which forms apply to your specific situation. They handle all of this — you only need to sign what they put in front of you.`),
      h2('The Medical Referee'),
      pt(`Every crematorium has a Medical Referee — a senior doctor who reviews all the paperwork before authorising the cremation. They are the final check that everything is in order. If anything is missing or unclear, they can require additional information before the cremation proceeds.`),
      h2('Registering the death'),
      pt(`Separate from the cremation paperwork, the death must be registered at the local register office within 5 days (8 in Scotland). The registrar issues the Death Certificate and the "Green Form" (Certificate for Cremation) that goes to the funeral director. Without this, the cremation cannot proceed.`),
      h2('Who handles it all'),
      pt(`Your funeral director handles all the cremation paperwork. You sign Form Cremation 10 (authority to cremate). The doctors complete forms 4 and 5 (or the coroner issues form 6). You register the death and the registrar issues the Green Form. The funeral director takes all of it to the crematorium. The Medical Referee reviews and authorises.`),
      CTA,
    ],
  },
  {
    slug: 'priority-care-collection',
    title: 'What Is a Priority Care Collection?',
    intent: 'informational',
    excerpt: 'Priority Care collections explained — when they are needed, what they cost, and why some providers don\'t include them.',
    bodyBlocks: [
      pt(`Priority Care is the term used for collecting someone who has died from somewhere other than a hospital or coroner's mortuary — most commonly from home, a care home, or a hospice. It carries an additional cost because it requires immediate response (often within hours) and additional staff to handle the collection sensitively.`),
      h2('When Priority Care is needed'),
      pt(`If the person has died at home, in a care home, in a hospice, or anywhere outside a hospital, a Priority Care collection is needed. The funeral director's collection team travels to the location and conducts the collection there. This typically happens within 4-12 hours of the call, often during evenings or weekends.`),
      h2('Why it costs more'),
      pt(`A hospital or coroner's mortuary collection is straightforward — the funeral director collects from a known, secure location during working hours. A Priority Care collection requires: response 24/7, two trained staff (always), specialist equipment (a stretcher and discreet vehicle), and the sensitivity of handling the moment in front of family. All of this adds cost.`),
      h2('What it costs'),
      pt(`At Best Direct Cremation, Priority Care is an optional £250 add-on if needed, taking the total to a maximum of £1,749. Many other direct cremation providers either don't offer Priority Care at all (you have to find your own way to get the deceased to them), or charge significantly more for it.`),
      h2('Hidden Priority Care fees'),
      pt(`Some direct cremation providers advertise a very low headline price (£950-£1,200) but then charge £500+ for Priority Care when it's needed. Always confirm the Priority Care fee before signing up. A £950 headline price plus £500 Priority Care fee is £1,450 — not much cheaper than a transparent £1,499.`),
      h2('What happens during a Priority Care collection'),
      pt(`Two professionally trained staff in dark, plain clothing arrive in an unmarked vehicle — no branded vans, no flashing lights, no spectacle. They speak quietly with the family, give them as much time as they need, then conduct the collection with dignity. The deceased is moved to the local funeral director's mortuary nearby — not transported hundreds of miles.`),
      h2('When you don\'t need Priority Care'),
      pt(`If the person died in hospital, in a hospice with mortuary facilities, or has been referred to the coroner (and is in the coroner's mortuary), a Priority Care collection is not needed. The funeral director collects from there during working hours at no extra cost.`),
      h2('What Best Direct Cremation includes'),
      pt(`At Best Direct Cremation, the £1,499 all-inclusive price covers a hospital or coroner's mortuary collection. The £250 Priority Care add-on covers collection from home, care home, hospice or anywhere outside a hospital. Maximum total: £1,749. No other hidden fees. No surprise charges.`),
      CTA,
    ],
  },
  {
    slug: 'green-funerals',
    title: 'Green and Eco-Friendly Funerals UK',
    intent: 'informational',
    excerpt: 'Green funerals, woodland burial and eco-friendly options in the UK — what is available, what it costs, and what to consider.',
    bodyBlocks: [
      pt(`A growing number of UK families want a funeral that reflects environmental values. There are real options — natural burial, alternative materials, lower-carbon cremation processes — but the market is fragmented and the choices are not always obvious. This guide explains what is genuinely available.`),
      h2('Natural and woodland burial'),
      pt(`Around 270 natural burial grounds exist in the UK (Association of Natural Burial Grounds, 2024). They differ from traditional cemeteries in important ways: no embalming, biodegradable coffins or shrouds, no headstones (often a tree or a wildflower meadow marker instead), and the ground gradually returns to a natural state. Costs vary by region — typically £900-£3,000 for the plot itself.`),
      h2('Biodegradable coffins'),
      pt(`A traditional MDF veneer coffin is the most-used option in the UK but is not particularly biodegradable. Greener options include: cardboard (very low impact, much cheaper, can be decorated), willow or wicker (woven natural fibres, very biodegradable, often visually beautiful), bamboo (similar to wicker), banana leaf, and pine shrouds (just a fabric wrap, used in some natural burials).`),
      h2('Lower-carbon cremation'),
      pt(`Standard cremation produces around 245kg of CO2 per cremation. Some UK crematoria have invested in heat recovery systems that use the cremator's waste heat to heat the building and reduce overall carbon footprint. New technologies like alkaline hydrolysis (water cremation, also called Resomation) produce a fraction of the carbon — but it is not yet widely available in the UK.`),
      h2('Direct cremation as a low-impact choice'),
      pt(`Direct cremation, by removing the hearse procession, the floral tributes, and many of the ceremonial elements, has a substantially lower carbon footprint than a traditional funeral. It is not strictly "green" in the eco-burial sense, but it is significantly lower-impact than the average UK funeral.`),
      h2('No embalming'),
      pt(`Most direct cremations do not involve embalming, which is the use of chemical preservatives (formaldehyde) in traditional funerals. Removing embalming makes the funeral genuinely lower-impact and is the norm in green burials.`),
      h2('Locally-sourced materials'),
      pt(`Some funeral directors source coffins and flowers locally rather than nationally — reducing transport miles. Ask if this matters to you. Best Direct Cremation's local network of funeral directors means short local distances by default — no centralised hub transport.`),
      h2('Memorial trees'),
      pt(`A popular eco-memorial: planting a tree (in a woodland, garden, or memorial scheme) in memory of the deceased. The Woodland Trust, the National Trust and many local councils run tree-planting memorial schemes from £50-£200.`),
      h2('Where to find specialist green funeral providers'),
      pt(`The Association of Natural Burial Grounds maintains a UK directory. The Natural Death Centre is the longest-established UK charity supporting green funerals and has an excellent guide. Some funeral directors specialise in green funerals — search "green funeral director [your area]".`),
      CTA,
    ],
  },
  {
    slug: 'funeral-flowers',
    title: 'Funeral Flowers — Etiquette, Costs and Alternatives',
    intent: 'process',
    excerpt: 'A guide to funeral flowers in the UK — what tributes to send, costs, and the growing trend of donations instead.',
    bodyBlocks: [
      pt(`Funeral flowers are one of the most visible parts of a traditional funeral — and one of the most variable in cost and meaning. They are not part of a direct cremation, but most families still want to mark the cremation with something. This guide explains the options.`),
      h2('Traditional funeral flowers'),
      pt(`At a traditional funeral, family flowers ("from the family") sit on top of the coffin. These typically cost £150-£500+ depending on size and design. Additional tributes from friends and other family members are often displayed at the crematorium or burial site. A sympathy bouquet sent to the family home typically costs £40-£80.`),
      h2('At a direct cremation'),
      pt(`There is no service at the crematorium, so no large floral displays. Many families instead place a single bouquet on the coffin before it leaves the funeral director — a private moment of farewell. Some families request that money be donated to a charity instead of flowers (see "Donations" below).`),
      h2('At a separate memorial'),
      pt(`If you're holding a memorial service after a direct cremation, flowers at the venue can transform the atmosphere. Many families choose meaningful flowers — the deceased's favourites, flowers from their garden, or simple wildflowers. Costs range from £30 for simple arrangements to £300+ for full venue displays.`),
      h2('What flowers to send'),
      pt(`White roses and lilies are the most traditional. Yellow flowers signify warmth and friendship. Mixed sympathy bouquets in pale colours are universally appropriate. Avoid red roses (associated with romantic love) unless that meaning is intended. The deceased's favourite flowers are always appropriate, regardless of tradition.`),
      h2('Costs'),
      pt(`Single sympathy bouquet delivered: £40-£80. Casket spray (large display on top of coffin): £150-£400. Standing wreath or cross: £80-£200. Letter tributes (the deceased's name or "DAD" in flowers): £150-£300. Full venue displays for a memorial: £200-£600+.`),
      h2('Donations instead of flowers'),
      pt(`Increasingly common — particularly at direct cremations and memorials. The family nominates a charity (often one connected to the deceased — a charity they supported, a charity related to their illness, or a local good cause). Attendees donate online or via the funeral director, often via a JustGiving "in memory" page. Many families find this far more meaningful than several hundred pounds of flowers that wilt in days.`),
      h2('Etiquette for senders'),
      pt(`If a notice says "family flowers only" or "donations to [charity] in lieu of flowers", respect that. The family has made a specific choice. If you want to mark the death personally, send a card and a separate donation to the named charity.`),
      h2('Local florists'),
      pt(`Use a local florist where possible — they understand local funeral traditions, can deliver to the right crematorium or address, and the money stays in the community. Avoid large national chains for time-sensitive funeral orders; quality and delivery reliability are highly variable.`),
      CTA,
    ],
  },
  {
    slug: 'when-someone-dies-abroad',
    title: 'When Someone Dies Abroad — What to Do',
    intent: 'process',
    excerpt: 'A guide to what to do if a UK family member or loved one dies abroad — registration, repatriation, costs, and practical steps.',
    bodyBlocks: [
      pt(`If a UK family member or close friend dies abroad, the practical and emotional weight is enormous. Distance, language barriers, foreign legal systems and high costs all combine to make this one of the hardest situations a family can face. This guide explains what to do, in what order, and where to get help.`),
      h2('Step 1 — Contact the British consulate'),
      pt(`The British embassy or consulate in the country where the death occurred is your first point of contact. They can: confirm the death to UK authorities, provide a list of local funeral directors and repatriation specialists, advise on local legal requirements, and put you in touch with translators if needed. Call the FCDO helpline on 0207 008 5000 (24/7).`),
      h2('Step 2 — Register the death locally'),
      pt(`The death must be registered in the country where it occurred, following that country's rules and procedures. This is normally done by the next of kin or by a local funeral director acting on the family's behalf. You'll need the local death certificate (in the local language) for almost everything afterwards.`),
      h2('Step 3 — Decide: bring them home or cremate locally?'),
      pt(`Two main options. Repatriation: the body is returned to the UK for cremation or burial. This is the most expensive option (£3,000-£10,000+ depending on the country, often higher) and takes 2-4 weeks. Local cremation: the cremation takes place in the country where the death occurred, and the ashes are returned to the UK (which is much cheaper and faster than repatriating a body — typically £500-£1,500).`),
      h2('Step 4 — Repatriation process'),
      pt(`If repatriating, you need: a specialist international funeral director (in the country where the death occurred or in the UK organising the inbound side), embalming (almost always required for international transport), a specialist coffin compliant with airline requirements, a copy of the death certificate (translated and apostilled — legally certified for international use), permission from the receiving country.`),
      h2('Step 5 — Funeral in the UK'),
      pt(`Once the body or ashes arrive in the UK, a normal UK funeral follows. If you've repatriated a body, you'll usually need a fresh UK death certificate (the registrar uses the original foreign certificate to issue a UK record). A UK direct cremation typically costs £1,499 — separate from the repatriation cost.`),
      h2('Insurance'),
      pt(`Most decent travel insurance includes repatriation cover. Check the deceased's policy immediately and contact the insurer's emergency line. If insurance is in place, the insurer often coordinates the entire repatriation. If there is no insurance, the family pays the full cost — which can be substantial.`),
      h2('Help and support'),
      pt(`The Foreign, Commonwealth & Development Office (FCDO) Bereavement Pack is comprehensive and free — search "death abroad GOV.UK". The British charity Samaritans (116 123) offers emotional support 24/7. UK-based international funeral directors include Kenyon International Emergency Services and Rowland Brothers International — they handle the practical logistics including all paperwork and transport.`),
      h2('Cost summary'),
      pt(`Local cremation abroad + ashes returned: £500-£1,500. Repatriation of body + UK funeral: £4,500-£10,000+. Insurance can cover most repatriation costs. The FCDO does not pay for funerals abroad except in genuine destitution cases.`),
      CTA,
    ],
  },
  {
    slug: 'bereavement-payments-and-benefits',
    title: 'Bereavement Payments and Benefits — UK Guide 2026',
    intent: 'legal',
    excerpt: 'What state benefits and payments are available to UK families after a bereavement in 2026.',
    bodyBlocks: [
      pt(`Several state benefits and payments are available to UK families after a bereavement — but few people know exactly what they qualify for. This guide explains every UK bereavement benefit available in 2026, who qualifies, and how to claim.`),
      h2('Bereavement Support Payment'),
      pt(`Replaced the previous Widowed Parent's Allowance and Bereavement Allowance in 2017. Available to spouses or civil partners (and from 2023, cohabiting partners with children) of someone who died while paying National Insurance. Two rates: a higher rate (£3,500 initial + £350 per month for 18 months) for those with children, and a lower rate (£2,500 initial + £100 per month for 18 months) for those without. Must claim within 21 months of the death.`),
      h2('Funeral Expenses Payment'),
      pt(`A means-tested payment for low-income families to help with funeral costs. Available to: people on certain benefits (Universal Credit, Pension Credit, Income Support, Housing Benefit, JSA, ESA, Working Tax Credit, Child Tax Credit). Covers: burial or cremation fees, certain travel costs, additional costs of moving the body. Typically £1,000-£1,500 depending on circumstances. Apply within 6 months of the funeral via GOV.UK.`),
      h2('Children\'s Funeral Fund'),
      pt(`If a child under 18 has died, the Children's Funeral Fund (England) covers most cremation or burial fees. Wales, Scotland and Northern Ireland have similar arrangements. There is no means test — every family qualifies. Speak to the funeral director, who applies on the family's behalf.`),
      h2('Bereavement Allowance — pre-2017 claims'),
      pt(`If you were already receiving Widowed Parent's Allowance or Bereavement Allowance before April 2017, your existing payments continue under the old rules. The above payments only apply to deaths from April 2017 onwards.`),
      h2('War Widow\'s or Widower\'s Pension'),
      pt(`For the spouse or civil partner of someone who died as a result of military service. A weekly pension that is normally tax-free. Apply via Veterans UK.`),
      h2('State Pension'),
      pt(`If the deceased was receiving State Pension, payments stop after death. The surviving spouse or civil partner may be entitled to inherit some of the deceased's State Pension entitlement — particularly for those reaching State Pension age before 6 April 2016 (under the old basic State Pension rules). Contact the Pension Service.`),
      h2('Private pensions'),
      pt(`Most private and workplace pensions pay a death benefit — either a lump sum, an ongoing pension to a dependant, or both. Each scheme is different. The deceased's pension paperwork or a phone call to the scheme administrator confirms what's available.`),
      h2('How to claim — Tell Us Once'),
      pt(`When you register the death, ask about "Tell Us Once" — a free government service that notifies most state bodies in one go. This automatically starts the process for many bereavement benefits. You'll be given a reference number to use within 28 days.`),
      h2('Where to get help'),
      pt(`Citizens Advice can walk you through every benefit you might qualify for. The Money and Pensions Service has a free guide. Your local council's welfare rights team can help with specific claims. Don't leave money on the table — the system is complex but the help is real.`),
      CTA,
    ],
  },
];

async function run() {
  console.log(`Ingesting ${HELP.length} help articles into ${PROJECT_ID}/${DATASET}…`);
  let count = 0;

  for (const a of HELP) {
    const doc = {
      _type: 'article',
      _id: `help-${a.slug.replace(/\//g, '-')}`,
      title: a.title,
      slug: { _type: 'slug', current: a.slug },
      section: 'help',
      intent: a.intent,
      excerpt: a.excerpt,
      body: enrichBody(a.bodyBlocks, a.slug),
      faqs: a.faqs?.map(f => ({ _type: 'faq', _key: f.q.slice(0,12).replace(/\s/g,''), question: f.q, answer: [pt(f.a)] })),
      lastReviewed: new Date().toISOString().split('T')[0],
    };
    await client.createOrReplace(doc);
    count++;
    console.log(`  ✓ /help/${a.slug}/`);
  }

  console.log(`\nDone. ${count} help articles created.`);
}

run().catch(err => { console.error(err); process.exit(1); });
